GoogleCloudPlatform/dotnet-docs-samples

.gitignore, bigquery/api/GettingStarted/BigQuery.csproj, bigquery/api/GettingStarted/packages.config, bigquery/api/GettingStarted/test/packages.config, bigquery/api/GettingStarted/test/test.csproj, buildAndRunTests.bat
Jenkins was reporting success even when some of the tests had failed, so
add a little logic to the batch script to fix that.
Then, fix the problem with the broken builds.
And add TestResults/ to .gitignore for convenience.
=> Fix the batch test script; fix GettingStarted build.

storage/api-veneer/QuickStartTest/QuickStartTest.cs
2 tests failed over the weekend because the timeout of 10+ seconds was not
long enough.
=> Keep retrying for longer.

logging/api/App.config, logging/api/LoggingSample.csproj, logging/api/LoggingTest/LoggingTest.csproj, logging/api/LoggingTest/app.config, logging/api/LoggingTest/packages.config, logging/api/Program.cs, logging/api/QuickStart/App.config, logging/api/QuickStart/QuickStart.csproj, logging/api/QuickStart/packages.config, logging/api/packages.config
The logging test fails sometimes due to random errors on the server like this:
`Grpc.Core.RpcException : Status(StatusCode=Internal, Detail="Internal error encountered.")`
When that happens, retry for 20 seconds.
First, upgrade to beta04, because the CallSettings syntax has changed between beta02 and beta04.
=> Fix flaky test

sessionstate/WebApp/Services/DatastoreSessionStateStoreProvider.cs
So our automated tests doesn't fill up our logs.
=> Stop writing log warnings when an operation takes too long.

vision/api/VisionTest/VisionTest.cs
The image file is sometimes left open between tests.  This attempts to fix
it.  I haven't been able to reproduce the issue locally.
=> Fix occaisonal Jenkins test failure.

vision/api/Detect/Detect.csproj, vision/api/Detect/Program.cs, vision/api/Detect/packages.config, vision/api/DetectFaces/DetectFaces.csproj, vision/api/DetectFaces/packages.config, vision/api/QuickStart/QuickStart.csproj, vision/api/QuickStart/packages.config, vision/api/VisionTest/VisionTest.csproj, vision/api/VisionTest/app.config, vision/api/VisionTest/packages.config
One breaking change: FromStorageUri has been renamed to
FromUri as it now accepts other URI formats (http/https).
This change does not demonstrate any of the new features (crop hints
etc).
=> Update to the latest Vision API

storage/api/Storage/Program.cs
Fixes https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/206
=> Move RandomBucketName() call out of storage_create_bucket sample.

BuildTools.psm1, logging/api/Program.cs
Until the logging API issues are fixed.
=> Don't throw an exception when a test times out.

appengine/flexible/README.md, endpoints/getting-started/README.md
Because there are so many confusing choices now.
=> Tell the user exactly which core SDK to download and install.

appengine/flexible/CloudSql-PostgreSql/Startup.cs, appengine/flexible/CloudSql/Startup.cs
Add new region tag "connection" for connection code block.
These files had 2 conflicting "example" region tags.
=> Fix duplicate region tag names

appengine/flexible/SocialAuth/Upload-UserSecrets.ps1
It was adding extra quotes around the values, which broke social auth.
=> Fix Upload-UserSecrets.ps1.

testutil/TestUtil.cs
So double the time those tests can take to pass.
=> Eventual consistency is still causing flaky tests.

endpoints/getting-started/openapi.yaml, endpoints/getting-started/src/IO.Swagger/deployTests.ps1
After conversation with the Endpoints team, this was the most effective solution we came up with to guide users through setting up Endpoints on App Engine. Having users uncomment code proved to be difficult. If you have another idea that could work better, please let me know. Otherwise, this will have to do.
=> Add openapi-appengine.yaml file for App Engine deployments.

spanner/api/Program.cs, spanner/api/QuickStart/QuickStart.csproj, spanner/api/QuickStart/packages.config, spanner/api/Spanner.csproj, spanner/api/SpannerTest/Tests.cs, spanner/api/packages.config
read_only_transaction_core
read_write_transaction_core
also adds a new tag for showing code on how to use the transient fault app block to handle transaction retries.
read_write_retry
(only one is needed as its the same in netcore and net45)
=> add new tags for netcore versions of transaction samples.

kms/api/CloudKmsTest/CloudKmsTest.cs, kms/api/Program.cs
In particular, this change:
- changes to use a consistent "Id" suffix for resource name components
- uses "plaintext" and "ciphertext" consistently to refer to unecrypted and encrypted data, respectively
- fixes some of the text that misspells "decrypt" and "encrypt"
Tracking bug: http://b/64758639
=> KMS: Make the samples consistent with the other languages.

bigquery/api/GettingStarted/App.config, bigquery/api/GettingStarted/BigquerySample.csproj, bigquery/api/GettingStarted/BigqueryTest/BigqueryTest.cs, bigquery/api/GettingStarted/BigqueryTest/BigqueryTest.csproj, bigquery/api/GettingStarted/BigqueryTest/app.config, bigquery/api/GettingStarted/BigqueryTest/packages.config, bigquery/api/GettingStarted/Program.cs, bigquery/api/GettingStarted/packages.config
Some old overloads are now obsolete; the changes here use the new
overload.
=> Update to BigQuery library 1.0.0-beta18

commandlineutil/Lib/CommandLineUtil.csproj, commandlineutil/Lib/VerbMap.cs, commandlineutil/Sample/CommandLineUtilSample.csproj, commandlineutil/Sample/Program.cs, commandlineutil/Sample/runTests.ps1, spanner/api/Program.cs, spanner/api/Spanner.csproj
So we can generally reuse it in other samples.  It has a number of advantages over calling `Parser.ParserArguments().MapResult()`:
1. It can handle more than 16 verbs.
2. You can call void functions in addition to functions that return a value.
3. You don't have to repeat the options type.  With .MapResult(), you have use the options type once in the template parameter list, and again in the lambda.
4. You'll see sane error messages if there's a typo.
Like TestUtil, .NET 4.6 projects must include the source file.  .NET core projects should add a reference to the library.
I'm not suggesting that we retrofit all the existing code to use this class.  But we should consider it when writing new code, and whenever we add new verbs to an old sample and cross the 16-verb boundary.
=> Factor VerbMap class out of Spanner sample.

pubsub/api/PubsubTest/PubsubTest.cs
So that multiple tests running at the same time won't interfere with each other.
=> Use randomNames in pubsub tests.

video/api/Test/Tests.cs, video/api/Test/runTests.ps1
Splitting the 'dotnet test' command into two separate 'dotnet build' and 'dotnet test --no-build' commands reduces the peak memory usage by about 190 MB.  Go figure.
=> Fix occasional out of memory errors in video test.

appengine/flexible/HelloWorld/app.yaml
We've gotten reports of unexpected costs from users that left the hello world running and had two standard instances running for a month. This keeps the costs to a minimum to kick the tires.
=> Keeping costs low

video/api/Analyze/Program.cs
Needs a blank line between AnalyzeLabels and PrintLabels, so that there's a line when they're combined in the docs.
=> Add blank line for doc rendering

.kokoro-windows/trampoline.ps1
msbuild is now claimed to be installed in the kokoro image, so try to build without installing it.
=> No need to choco install msbuild.

iot/api/Program.cs
Related:
* GoogleCloudPlatform/ruby-docs-samples#243
* GoogleCloudPlatform/java-docs-samples#1041
* GoogleCloudPlatform/golang-samples#401
=> Cleanup Cloud IoT region tags.

pubsub/api/PubsubTest/PubsubTest.cs
That was a bug.  It should definitely retry test when the topic is not found, because it hasn't been created yet.  And yes, this should help remove flakiness.
Also, show more realistic values for the backoff.
Change-Id: I37e8b2690277ead246630307f6ce19b85ffe352d
=> Retry the pub/sub test when StatusCode.NotFound.

logging/api/LoggingTest/LoggingTest.cs
Due to eventual consistency.  Fix it with an Eventually().
Change-Id: I6aa0471336089b20a15b6c8ee3785b82960013df
=> TestDeleteLog() was flaky.

endpoints/getting-started/src/IO.Swagger/app.yaml
We introduce a new feature where we can specify in YAML that service configuration for Endpoints is going to be managed. This means that the service will pull latest deployed service configuration automatically, rather than requiring customer to specify specific version of service configuration.
New flag:
**--rollout_strategy=managed**
Previously the only way to specify a version was using the following flag:
**--version=SERVICE_CONFIG_ID**
=> [DO NOT MERGE] Change to endpoints managed rollout

monitoring/api/AlertSample/Program.cs
Adds region tags to Program.cs, for extraction of doc samples without resorting to regexps.
=> Adds region tags to C# alerting sample

monitoring/api/AlertSample/Program.cs
Moved tags to fix the inadvertent clipping of a brace from an example.
=> Minor update to region tags

bigquery/api/BigqueryTest/BigqueryTest.cs
Updates to standard region tags to enable accurate tracking of BigQuery samples. Also deletes unused samples.
These samples all have commit branches specified for devsite, so this PR will not break any sample rendering. After this PR is merged, I will update the region tags and commit branches on devsite.
=> BigQuery: Updates to standard region tags and deletes unused samples

dialogflow/api/Test/ContextManagementTests.cs, dialogflow/api/Test/DialogflowTest.cs, dialogflow/api/Test/EntityManagementTests.cs, dialogflow/api/Test/EntityTypeManagementTests.cs, dialogflow/api/Test/IntentManagementTests.cs, dialogflow/api/Test/SessionEntityTypeManagementTests.cs, dialogflow/api/Test/runTests.ps1
Also, RetryRobot makes dialogflow tests cope with eventual consistency in the list() method.
=> Throttle dialogflow calls.

monitoring/api/AlertSample/Program.cs, monitoring/api/AlertTest/runTest.ps1
I needed these tools to clean up policies and channels left behind by tests.
Also, fix https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/546
=> Samples to delete alert policies and notification channels.

dialogflow/api/Test/DialogflowTest.cs
Test is still failing regularly because we exceed request per minute quota.
When the test exceeds quota, back off for a minute or so.
=> Back off when dialogflow test exceeds quota.

applications/sudokumb/WebAppTest/WebAppTest.cs
Retry robot was not actually retrying because I forgot to list the
type of exceptions to retry.
=> Fix Sudokumb test.

datastore/api/TaskList/Program.cs, datastore/api/TaskListTest/DatastoreTest.cs
These samples/region tags aren't used on cloud.google.com, so I'm deleting them.
Related:
- GoogleCloudPlatform/python-docs-samples#1531
- googleapis/nodejs-datastore#110
- GoogleCloudPlatform/java-docs-samples#1138
- GoogleCloudPlatform/php-docs-samples#631
- GoogleCloudPlatform/ruby-docs-samples#292
- GoogleCloudPlatform/golang-samples#516
=> Delete unused Datastore region tags / samples.

spanner/api/Spanner/Program.cs, spanner/api/Spanner/Spanner.csproj
Enterprise library retry nuget package targets .NET Framework 4.6.1. If we reference it, we won't be able to run the code on Linux. We could (potentially) depend on testUtil project that includes retryRobot implementation, but that means that Spanner project has to pull many unnecessary nuget packages for GCP.
Therefore, I've added a tiny implementation of retryRobot and used it to replace retry code from Enterprise library.
=> Fixing Spanner code to not depend on enterprise library nuget packages

texttospeech/api/TextToSpeech/TextToSpeech.cs
Fixing the parameter description in the comments for ListVoices() on this page:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/texttospeech/api/TextToSpeech/TextToSpeech.cs
=> Changes ListVoices parameter description

monitoring/api/UptimeCheckSample/Program.cs
It can take a long time, causing tests to fail.
Server-side issue tracked in bug 112552528.
=> Extend the timeout to call CreateUptimeCheckConfig.

monitoring/api/MonitoringTest/MonitoringTest.cs, monitoring/api/QuickStart/QuickStart.cs
Because writing a custom metric is limited to once per minute.
Change-Id: I98f6468953bd3fd6d87cbc9f57ab5d5717a3e1c7
=> Write the custom metric only once per test run.

storage/api/README.md, storage/api/Storage/Storage.cs, storage/api/Storage/Storage.csproj, storage/api/StorageTest/StorageTest.cs
=> [Storage] Bucket lock samples

.kokoro-windows/New-BuildEnv.ps1, applications/sudokumb/WebAppTest/WebAppTest.cs
Version 2.37 is a few months old, but it's a known good version, and our selenium test started failing with no changes to code or test VM image.
=> Fix selenium test with --no-sandbox.

storage/api/StorageTest/StorageTest.cs
I think there's a race condition where move sometimes fails to find a very-recently uploaded file.
=> Deflake StorageTest.TestMove().

appengine/flexible/HelloWorld/Startup.cs, appengine/flexible/HelloWorld/app.yaml, appengine/flexible/HelloWorld/appsettings.json
ASP.NET frequently uses environment variable names with colons.
Change-Id: I3f8cdd68e635fd86fce33ff5bcc47409f5f2af2c
=> Show how to set an environment variable name with a colon.

.kokoro-windows/New-BuildEnv.ps1
By specifying a version of selenium-chrome-driver that is known to work with the version of chrome installed on the Kokoro test machines.
=> Fix broken test.

iot/api/CloudIotMqttExample/Program.cs
This should fix some issues we're having in the documentation introduced by un-matched / overmatched tags in the MQTT sample.
=> Cleans up start ... end tags

bigtable/api/TableAdminExample/TableAdmin.cs
Fixes #794
Additionally, add whitespace in object initializers to be consistent with other code.
(I can separate the two into separate commits if you'd prefer.)
=> Fix comment on a GC rule to match the code

bigquery/api/Snippets/CopyTable.cs, bigquery/api/Snippets/ExtractTable.cs, bigquery/api/Snippets/ExtractTableJson.cs, bigquery/api/Snippets/LoadFromFile.cs, bigquery/api/Snippets/LoadTableGcsCsv.cs, bigquery/api/Snippets/LoadTableGcsJson.cs, bigquery/api/Snippets/LoadTableGcsOrc.cs, bigquery/api/Snippets/LoadTableGcsOrcTruncate.cs, bigquery/api/Snippets/Query.cs, bigquery/api/Snippets/QueryLegacy.cs
- Always assign back to a variable
- Always throw on any error
The return value of PollUntilCompleted() is important; ignoring it leads to issues such as https://github.com/googleapis/google-cloud-dotnet/issues/3169#issuecomment-505347038
The samples now always use the return value; I'm going to update the XML documentation as well. Any suggestions for further action would be welcome too.
=> Improvements for samples of job polling

firestore/api/GetData/Program.cs
A QuerySnapshot only consists of existing documents, so there's no need to check DocumentSnapshot.Exists.
=> Remove unnecessary `Exists` checks.

logging/api/LoggingTest/LoggingTest.cs
The delete-log command fails because it can't find the newly created log yet.  Eventual consistency takes too long.
=> Skip TestDeleteLog because it takes too long for the log to appear.

.kokoro/main.ps1
The problem was that the list of directories selected from the groups was not getting flattened.  The code tried to flatten the list, but it did not work as intended.  Fix that code.
For example, when intending to run group 1, tests from group 3 were also getting run.
https://fusion.corp.google.com/runanalysis/test/prod%3Acloud-devrel%2Fdotnet-docs-samples%2Flinux%2Fsystem_tests/prod%3Acloud-devrel%2Fdotnet-docs-samples%2Flinux%2Fsystem_tests/KOKORO/d5a45250-0025-4a19-8a95-131b80771737/1571664738575/build%20%238118/Targets?target=cloud-devrel%2Fdotnet-docs-samples%2Flinux%2Fsystem_tests&drilldownTab=tests
Change-Id: I0ee0b7df45cec908a68f19b5cf1207b2d00c7e17
=> Fix: Wrong list of directories chosen for kokoro build.

storage/api/QuickStart/QuickStart.cs
`StorageClient` is disposable, this PR adds a `using` statement to ensure it is properly disposed of.    In this particular app it isn't an issue but if, like me, you copy this code into a high throughput application you will eventually get exceptions due to `HttpClient` running out of available TCP ports.
=> Storage quickstart now disposes of StorageClient

vision/api/Detect/Detect.csproj, vision/api/Detect/Program.cs, vision/api/VisionTest/VisionTest.cs
This pull request adds the following region_tag:
vision_set_endpoint
The canonical sample is here:
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2569
=> Vision OCR multi-region

bigquery/api/Snippets/AuthenticateServiceAccount.cs, bigquery/api/Snippets/Snippets.csproj, bigquery/api/Snippets/Test.cs
This pull request adds the following region tag:
- bigquery_client_json_credentials
The Python canonical is here:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/1a87fb3e076d60ec6bde274c9aecf7dc5296a43b/bigquery/cloud-client/authenticate_service_account.py
=> Adds explicit authentication with JSON credentials to BQ snippets

dialogflow/api/Test/DetectIntentTextsTest.cs, dialogflow/api/Test/DialogflowTest.cs, dialogflow/api/Test/EntityTypeManagementTests.cs, dialogflow/api/Test/SessionEntityTypeManagementTests.cs, dialogflow/api/Test/runTests.ps1
Dialogflow tests have been off for a while because they were failing because they had reached quota in entity and intent they could create.
All tests now clean up after themselves.
Still one test is off because it is failing, see #935 .
=> [Dialogflow]: Cleanup after some tests so as to not use up quota.

language/api/Analyze/Program.cs
These changes removes a static using statement in the Natural Language samples and replaces instances of the Features class with the more qualified AnnotateTextRequest.Types.Features.
This affects the following regions tags / code snippets:
- language_syntax_gcs
- language_syntax_text
=> Changes references to Features type to be more qualified

translate/api/QuickStart/Program.cs, translate/api/Snippets/TranslateText.cs
This updates two code samples:
- [START translate_translate_text]
- [START translate_quickstart]
This change allows the console to output non Latin characters (e.g. Cyrillic, Chinese, Greek).
=> Specifies UTF-8 encoding for output of Translation response 

dialogflow/api/Test/runTests.ps1
=> [Dialogflow] Disables tests because they were reaching quota.

firestore/api/FirestoreTest/FirestoreTest.cs, firestore/api/FirestoreTest/FirestoreTest.csproj, firestore/api/FirestoreTest/runTests.ps1, firestore/api/SolutionCounter/Program.cs, firestore/api/SolutionCounter/SolutionCounter.csproj
Previously made samples for [Go](https://github.com/GoogleCloudPlatform/golang-samples/pull/959) and [Python](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2412) are already merged and posted to Distributed Counters page, so, as promised, I'm pushing similar samples for C#.
=> docs(firestore): add samples for distributed counters

speech/api/Recognize/Recognize.cs
Speech-to-Text now supports more enhanced models than just phone_call. The comment in the samle needs to be updated to reflect this.
This pull request affects the following region tags:
- speech_transcribe_enhanced_model
=> fix: removed not about supported enhanced models for Speech-to-Text

compute/sqlserver/powershell/README.md, compute/sqlserver/powershell/create-availability-group.ps1, compute/sqlserver/powershell/create-sql-instance-availability-group-cleanup.ps1, compute/sqlserver/powershell/create-sql-instance-availability-group-prerequisites.ps1, compute/sqlserver/powershell/create-sql-instance-availability-group.Tests.ps1, compute/sqlserver/powershell/create-sql-instance-availability-group.ps1, compute/sqlserver/powershell/parameters-config.ps1, compute/sqlserver/powershell/validate-availability-group.ps1
Changed the scripts to use Alias IP ranges. This makes the process simpler as we no longer need to create routes to trick Windows into using the two extra IPs needed to set up Availability Groups. Now we just assign two extra IPs to the SQL Server VMs.
=> Changed scripts to use Alias IP ranges

.kokoro/main.ps1, auth/Auth.sln, auth/AuthSample/Program.cs, auth/AuthTest/AuthTest.cs, auth/AuthTest/AuthTest.csproj, dlp/api/DlpSample/DlpSample.csproj, dlp/api/DlpSample/RedactSamples.cs, dlp/api/DlpTest/DlpTest.csproj, iam/api/Access/Access.csproj, iam/api/AccessTest/AccessTest.csproj, iam/api/CustomRolesTest/CustomRolesTest.csproj, iam/api/Iam.sln, iot/api/CloudIotMqttExample/CloudIotMqttExample.csproj, iot/api/CloudIotMqttExample/Program.cs, iot/api/CloudIotMqttExampleTest/CloudIotMqttTest.cs, iot/api/CloudIotMqttExampleTest/CloudIotMqttTest.csproj, iot/api/CloudIotSample/CloudIotSample.csproj, iot/api/CloudIotSample/Program.cs, iot/api/CloudIotTest/CloudIotTest.cs, iot/api/CloudIotTest/CloudIotTest.csproj, jobs/api/v3/JobsTest/JobsTest.csproj
Some of the tests projects had dependencies on explicit versions of the Apiary libraries instead of on the projects containing the samples for the Apiary libraries. With the latest Apiary releases, version conflicts appeared.
Similar issues with external libraries like Newtonsoft.Json.
And, cleared some unused dependencies as well.
A similar thing will probably happen when we release gRPC libraries in the comming weeks.
=> Dependency cleanup on several projects.

.kokoro-windows/Initialize-GoogleProjectForTesting.ps1
This is what I get for going from memory rather than consulting the
docs:
https://cloud.google.com/kms/docs/reference/permissions-and-roles#predefined_roles
=> Fix invalid permission name

.kokoro/docker/Dockerfile
Keeping the previous version as well.
=> Installs .NET Core 3.1 on Docker image used for CI.

.kokoro-windows/New-BuildEnv.ps1
Towards #1013.
Makes then Windows environment used for testing support .NET Core 3.1.
* Stop supporting .NET Core 1.1 as well.
=> Makes the Windows environment used for testing support .NET Core 3.1.

identity-aware-proxy/IAPClientTest/runTest.ps1
=> [IAP]: Skips IAP testing because the application it was being tested against has dissapeared.

dialogflow/api/Test/DetectIntentTextsTest.cs, dialogflow/api/Test/runTests.ps1
Changes DetectIntentTextsTest so that it checks for snippet string literals rather than API output.
**Note:** This PR partially re-enables tests for the Dialogflow project (see #947). It filters the tests to select only the DetectIntentTextsTest.  I will adjust the filter as I re-enable more of the DF tests.
Fixes #935
=> fix: renables and fixes DetectIntentTextsTest

bigquery/api/Snippets/CreateJob.cs, bigquery/api/Snippets/Test.cs
This sample adds the following region tag:
* bigquery_create_job
The Python canonical sample is here:
https://github.com/googleapis/python-bigquery/blob/master/samples/create_job.py
=> feat: adds create BigQuery job sample

spanner/api/SpannerTest/Tests.cs
This was one of the latest tests to cause a presubmit test timeout.
Updates #1065
=> fix: skip TestUpdateBackup test

bigquery/api/Snippets/CreateJob.cs, bigquery/api/Snippets/Test.cs
- Change the quick start metric to `custom.googleapis.com/my_metric` 
- Change the type to "gce_instance".
Justification: Cloud monitoring api team discourage using "global" resource type for custom metric, and to align the sample, I change the metric type also.
=> fix-it(Cloud Monitoring Api): Change the quick start documentation.

spanner/api/Spanner/Program.cs
[PR#1111](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1111) failing [TestDeleteSampleData](https://source.cloud.google.com/results/invocations/873b1a6a-39fd-4d49-b254-817029ee8a3a/targets/github%2Fdotnet-docs-samples%2Fspanner%2Fapi%2FSpannerTest%2FTestResults/tests) Test as in sample was not added `await` while deleting the tables.
It's giving below error:
`Error: Google.Cloud.Spanner.Data.SpannerException : Cannot drop table UpcomingSingers with interleaved tables: UpcomingAlbums.`
=> fix(spanner): DeleteSampleData sample

spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
Refer comment [here](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1178#issuecomment-690140550)
=> [Spanner]: reduce time to delete the old databases and backups to 48 hrs

functions/firebase/FirestoreReactive/Function.cs
(It's a pity that it's tagged as Firebase when it's actually Firestore, but never mind... that's the tag everything uses.)
=> Give the Firestore Reactive sample the correct tag

firestore/api/QueryData/Program.cs
This doesn't have a test, as it requires an index to execute without error. I've tested it locally though.
Fixes #1183.
(The Firestore samples in general need to be overhauled somewhat, but that can come separately.)
=> Add Firestore Collection Group Query sample

spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
Fixes #1189 
Before starting the test Check the databases available on instance, if it's more than  94 delete the old five databases.
Removed delete backup logic as we have separate database for same and we never delete it.
=> [Spanner]: Delete five oldest databases if instance reaches the database limit

run/helloworld/.gcloudignore
#1196 removed this gcloudignore, which is used directly in the Cloud Run quickstart.
Since I am looking at this, I added some more context preamble and exclusion on git history matching some of the other gcloudignores in the Cloud Run samples.
This is in `run/helloworld/` instead of `run/` because in Q4 we plan to move the Cloud Run C# quickstart here.
=> fix(run): restore missing gcloudignore

functions/helloworld/HelloHttp/Function.cs, functions/helloworld/HelloWorld.Tests/HelloHttpTest.cs
It's a shame this is more long-winded, but we don't really want to
log an exception every time there's an empty request.
=> Don't parse request body when there isn't one

applications/leaderboard/Leaderboard/Leaderboard.csproj, applications/leaderboard/Leaderboard/Program.cs, applications/leaderboard/LeaderboardTest/LeaderboardTest.csproj, applications/leaderboard/LeaderboardTest/Tests.cs, applications/leaderboard/LeaderboardTest/runTests.ps1, applications/leaderboard/README.md, applications/leaderboard/step4/Leaderboard.csproj, applications/leaderboard/step5/Leaderboard.csproj, applications/leaderboard/step5/Program.cs, applications/leaderboard/step6/Leaderboard.csproj, applications/leaderboard/step6/Program.cs
- Updates insert methods to use RunWithRetriableTransactionAsync()
- Updates Google.Cloud.Spanner.Data to latest version
- Shortens test time
=> Fix Cloud Spanner Leaderboard test flakiness.

securitycenter/api/src/CreateNotificationConfigSnippets.g.cs, securitycenter/api/src/DeleteNotificationConfigSnippets.g.cs, securitycenter/api/src/GetNotificationConfigSnippets.g.cs, securitycenter/api/src/ListNotificationConfigSnippets.g.cs, securitycenter/api/src/UpdateNotificationConfigSnippets.g.cs
Standardizing Security Command Center samples to use 'securitycenter' prefixing. 
- Wrapped existing samples to keep published doclinks unbroken
- Replace region tags that aren't published. 
Once this PR is through, published sample inclusions will be updated to use the new prefix, then I'll come through again and remove the unused block wraps.
=> docs: Wrap samples with future prefix

spanner/api/Spanner/GetBackupOperations.cs, spanner/api/Spanner/GetBackups.cs, spanner/api/Spanner/RestoreDatabase.cs
These samples' region tags slightly differ from identical snippets in different languages. The following is the remedy:
1. Merge this PR to fix GitHub source (keep old tag for now)
2. Fix doc code includes to represent the better region tag
3. Submit a second PR to clean-up redundant region tag wrapping
=> docs: homogenize region tags

iam/api/Access/AddMember.cs, spanner/api/Spanner/GetDatabaseOperations.cs
Making this change to standardize the region tag. Once this is merged, doc includes will be updated, then I'll come back through and remove inner tags.
=> docs: update some region tags missed in PR 1233

iam/api/Access/AddMember.cs, spanner/api/Spanner/GetBackupOperations.cs, spanner/api/Spanner/GetBackups.cs, spanner/api/Spanner/GetDatabaseOperations.cs, spanner/api/Spanner/RestoreDatabase.cs
Finalizing the work started in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1233 and https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1236. This PR removes "inner" tags now that the new tagging is live in docs.
=> docs: cleanup tagging

identity-aware-proxy/IAPClient/IAPClient.cs, identity-aware-proxy/IAPClientTest/IAPClientTests.cs, identity-aware-proxy/IAPClientTest/IAPFixture.cs, identity-aware-proxy/IAPClientTest/IAPTokenVerificationTests.cs
The [docs](https://cloud.google.com/iap/docs/authentication-howto#obtaining_an_oidc_token_for_the_default_service_account) where this sample is surfaced refers to using default credentials only.
=> feat(IAP): Changes the IAP sample to use Application Default Credentials.

spanner/api/Spanner.Samples.Tests/LogCommitStatsAsyncTest.cs, spanner/api/Spanner.Samples/LogCommitStatsAsync.cs, spanner/api/Spanner.Samples/Spanner.Samples.csproj
Adds a sample for `LogCommitStats` for Spanner.
=> feat: add LogCommitStats sample for Spanner

spanner/api/Spanner/Program.cs
The `spanner_create_table_with_datatypes` should create a table with all supported data types in Cloud Spanner. The .NET samples (as well as some other client languages) missed a `NUMERIC` column as this data type was added later than the originally supported data types. This change adds a `NUMERIC` column to the sample to bring it up to date with the samples of
the other client languages, and to bring it in line with the description of the sample.
See also https://cloud.google.com/spanner/docs/samples/spanner-create-table-with-datatypes#spanner_create_table_with_datatypes-java
Fixes #1254
=> feat: add NUMERIC column to table with all data types

spanner/api/Spanner.Samples.Tests/CreateBackupTest.cs, spanner/api/Spanner.Samples.Tests/SpannerFixture.cs, spanner/api/Spanner.Samples/CreateBackup.cs
Use the earliest version time of the test database instead of the local system time to ensure that the chosen version time is valid.
Fixes #1262
=> fix: use earliest version time for CreateBackup

applications/clouddemo/net4/Dockerfile, applications/clouddemo/net4/README.md, applications/clouddemo/net4/deployment.yaml, applications/clouddemo/netcore/README.md, applications/clouddemo/netcore/deployment.yaml
* Use placeholder as image name
* Use LTSC tag for Windows base image
=> Remove hardcoded image name in CloudDemo manifests

asset/quickstart/ExportAssetsTest/runTests.ps1
Fixes #1273
Default timeout is 300 seconds, so this doubles it.
=> ci(assets): Increase test timeout for exporting assets.

spanner/api/Spanner.Samples.Tests/CreateBackupTest.cs
Instead of using the earliest version time of the database, uses the current time (from spanner). If we used the earliest version time of the database instead we would be creating an empty backup, since the database we are backing up is not 1 hour old (default version retention period).
=> samples(spanner): PITR samples backup fix

eventarc/audit-storage/README.md, eventarc/pubsub/PubSub.csproj, eventarc/pubsub/README.md, eventarc/pubsub/Startup.cs
Both CloudNative.CloudEvents and Google.Events.Protobuf have
changed significantly since this sample was originally written.
The `gcloud eventarc` command is now GA, but creating a trigger with
a `matching-criteria` parameter still requires the `beta` component.
=> Update Eventarc sample to use latest libraries

functions/firebase/FirestoreReactive/FirestoreReactive.csproj, functions/imagemagick/ImageMagick/ImageMagick.csproj, functions/slack/SlackKnowledgeGraphSearch/SlackKnowledgeGraphSearch.csproj
This avoids using old (huge) versions of Grpc.Core.
=> chore: Update API client library dependencies in Functions samples

spanner/api/Spanner.Samples.Tests/CreateInstanceTest.cs
The `CreateInstance` test should be retried if the error that is returned is `Unavailable`. `Unavailable` can be returned by any RPC, and should normally be retried automatically for idem-potent RPCs. `CreateInstance` is not idem-potent, and is therefore not retried automatically. In this test however we can safely retry it without checking the status of the backend, as the test expects an `AlreadyExists` error to be returned.
Fixes #1332
=> test: retry CreateInstance test on Unavailable

storage/api/Storage.Samples.Tests/ActivateHmacKeyTest.cs, storage/api/Storage.Samples.Tests/BucketFixture.cs, storage/api/Storage.Samples.Tests/CreateHmacKeyTest.cs, storage/api/Storage.Samples.Tests/DeactivateHmacKeyTest.cs, storage/api/Storage.Samples.Tests/DeleteHmacKeyTest.cs, storage/api/Storage.Samples.Tests/GetHmacKeyTest.cs, storage/api/Storage.Samples.Tests/HmacKeyManager.cs, storage/api/Storage.Samples.Tests/ListHmacKeysTest.cs
And moves the cleanup to individual Dispose methods so that tests themselves are not delayed.
Note: HMAC keys need to be deleted inmediately because only 5 are allowed per service account.
Fixes #1272
=> refactor(Storage): Retries HMAC key cleanup.

spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
Else, databases won't be deleted with active backups (it seems).
=> tests: Delete backups before deleting database.

.github/renovate.json
- #992 tracks Bigtable samples modernization.
- #1004 tracks AppEngine samples modernization.
- #1426 tracks Endpoints samples modernizaton.
- #1427 trackes Google Home samples modernization.
Closes #1434
Closes #1430
=> build: Ignore dependecy updates for apps that need modernization.

storage/api/Storage/Storage.csproj
This is just we can avoid conflicts in #1201 which deletes this file anyway. And we don't have access to that PR's branch anymore.
=> chore(storage): Undo dependecy update

compute/api/Compute.Samples.Tests/ComputeFixture.cs, compute/api/Compute.Samples.Tests/ListImagesAsyncTest.cs, compute/api/Compute.Samples.Tests/ListImagesPerPageAsyncTest.cs, compute/api/Compute.Samples/Compute.Samples.csproj, compute/api/Compute.Samples/CreateInstanceAsync.cs, compute/api/Compute.Samples/ListAllInstancesAsync.cs, compute/api/Compute.Samples/ListImagesAsync.cs, compute/api/Compute.Samples/ListImagesPerPageAsync.cs, compute/api/Compute.Samples/ListZoneInstancesAsync.cs
Updates Google.Cloud.Compute.V1 dependency.
Closes #1438
=> feat(Compute): Use paginated lists.

compute/api/runTests.ps1
This is why timeout was not having any effect.
=> tests(Compute): Load tools from the correct path.

media/transcoder/api/Transcoder.Samples.Tests/TranscoderFixture.cs
Some of the jobs are still running when we stop retrying.
We might need to increase the overall timeout after this change.
=> tests(transcoder): Retry some more the job poller.

spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
We were deleting some instances being used. We are now deleting all instances that are older than 5 hours, tests take roughly 30 minutes to run.
=> tests: Improve how we delete stale instaces

spanner/api/Spanner.Samples.Tests/ListBackupOperationsTest.cs
Seems the API has stopped acceting metadata.database as part of the filer. We are looking into it. See #1583
=> tests(Spanner): Deactivates test for listing backup operations.

logging/api/LoggingSample/Program.cs
Remove extraneous sinkRequest references based on a different method of creating a Sink than the one being demonstrated.
=> chore: Remove dead code from CreateSink sample

bigtable/api/BigtableTest/runTests.ps1, bigtable/api/SnippetsTest/runTest.ps1
=> tests: Skip Bigtable samples tests as dependencies are now too old.

asset/api/Asset.Samples.Tests/Asset.Samples.Tests.csproj, asset/api/Asset.Samples/Asset.Samples.csproj, bigquery/api/SimpleApp/SimpleApp.csproj, bigquery/api/Snippets/Snippets.csproj, bigquery/data-transfer/api/QuickStart/QuickStart.csproj, bigquery/data-transfer/api/QuickStartTest/QuickStartTest.csproj, dlp/api/Snippets.Tests/Snippets.Tests.csproj, dlp/api/Snippets/Snippets.csproj, testutil/testutil.csproj
Some of these need to be updated together, or the target framework updated. Renovate does not know to do that.
=> Update some GAX V4 dependencies.

run/pubsub/Run.Samples.Pubsub.MinimalApi.Tests/PostHandlerTests.cs, run/pubsub/Run.Samples.Pubsub.MinimalApi.Tests/Run.Samples.Pubsub.MinimalApi.Tests.csproj, run/pubsub/Run.Samples.Pubsub.MinimalApi/.gcloudignore, run/pubsub/Run.Samples.Pubsub.MinimalApi/Dockerfile, run/pubsub/Run.Samples.Pubsub.MinimalApi/Program.cs, run/pubsub/Run.Samples.Pubsub.MinimalApi/Run.Samples.Pubsub.MinimalApi.csproj, run/pubsub/Run.Samples.Pubsub.sln, run/pubsub/runTests.ps1
Example that logs a simple Pub/Sub message consistent with examples from other frameworks.
Provides the code to implement the tutorial at https://cloud.google.com/run/docs/tutorials/pubsub
Implemented with .NET 6 and Minimal APIs.
=> feat(run/pubsub): add Cloud Run sample for Pub/Sub tutorial

run/markdown-preview/Samples.Run.MarkdownPreview.Editor/Controllers/RenderController.cs
Caught this mistake while updating the docs.  Oops.
=> fix(run/markdown-preview): fix typo 'Repsonse --> Response'

applications/clouddemo/net4/deployment.yaml, applications/clouddemo/netcore/deployment.yaml
Use networking.k8s.io/v1 instead of extensions/v1beta1
as the latter is no longer supported in recent GKE/
Kubernetes versions.
=> Use new Ingress resource for CloudDemo app

retail/interactive-tutorial/TestResourcesSetupCleanup/CreateTestResources.cs
Fixed creation a GCS bucket with `user_events_some_invalid.json` file.
Fixed creation a GCS bucket with `products_some_invalid.json` file.
=> Create json files in buckets with invalid product/event

media/livestream/api/LiveStream.Samples.Tests/LiveStreamFixture.cs
=> fix(Live Stream): delete inputs and channels more than 2 hours old

retail/interactive-tutorial/RetailSearch.Samples.Tests/SearchWithQueryExpansionTest.cs
With the test query and page size 10 our backend only returns 1 page of result currently. Fix the test case to only check the first page.
=> fix(Retail): Fix SearchWithQueryExpansionTest

cdn/signUrl/SignUrlSample.Tests/SignUrlSample.Tests.csproj, cdn/signUrl/SignUrlSample/SignUrlSample.csproj, error-reporting/api/ErrorReportingSample/ErrorReportingSample.csproj, error-reporting/api/test/test.csproj
So that we can update Microsoft.Net.Test.Sdk to 17.4.0 which this PR already does for the changed projects.
=> build: Update a few projects to netcoreapp3.1

firestore/api/ManageIndexes/Program.cs
Note: these are not used, according to my tracking sheet, so let's see if SnippetBot agrees. :) 
Context: [go/firestore-region-tags-normalization-2020q4](https://goto.google.com/firestore-region-tags-normalization-2020q4)
=> chore(firestore): update region tags to use product prefix

retail/interactive-tutorial/RetailSearch.Samples.Tests/SearchWithQueryExpansionTest.cs
The query expansion search result on the backend is not stable and the returned results may change over time. Tried to remove the strong result checks, and only check if query expansion is enabled in the search response, if the users request to enable query expansion.
Fixes #2047
=> chore(samples): fix retail query expansion tests

.kokoro-windows/New-BuildEnv.ps1
Specifying just `dotnetcore-sdk` is failing to install .NET Core 3.1 even though that's what Chocolatey shows as an example. Let's be explicit instead.
=> ci: Explicitly specify .NET Core 3.1 on setup

.kokoro-windows/New-BuildEnv.ps1
This seems to be needed for the latest .NET Core 3.1 SDK as it is needed for .NET 6.
=> ci: Upgrade chocolatey extensions before installing .NET SDKs

storage/api/Storage.Samples/MakePublic.cs
Addressing this TODO: remove the storage_set_bucket_public_iam tag later as it is already declared in MakeBucketPublic.cs
=> chore(storage): remove nested region tag

cdn/signUrl/SignUrlSample/Program.cs
Cloud CDN Snippets are missing product's specific region tags. In this PR, we are only adding region tags. No code changes. For more details, refer to [b/264905390](b/264905390).
=> fix: Add missing product region tags for Cloud CDN snippets

identity-aware-proxy/IAPClient/IAPTokenVerification.cs
Also explicitly specify that the IAP keys should be used to verify the signature.
Basically by not explicitly specifying these properties, it is hypothetically possible for an attacker to use a non-IAP token to talk to a IAP-protected application. If an attacker were able to get a token signed by Google for a user of the IAP-protected application, the attacker could impersonate the user. This would only be possible if the application exposed its non-IAP-protected endpoint, so hopefully its unlikely.
Here is an example of how the sample token authentication code will incorrectly accept a non IAP token. In this example a GCP service account token is used. Its subject will not match an IAP token, so it probably will not fool a relying party. …
=> Validate that the IAP JWT was actually issued by IAP

dlp/api/Snippets.Tests/DeidentifyDataUsingRedactWithMatchedInputValuesTests.cs, dlp/api/Snippets/DeidentifyDataUsingRedactWithMatchedInputValues.cs
- Added sample for [deidentify data using redact with matched input values](https://cloud.google.com/dlp/docs/samples/dlp-deidentify-redact) and added unit tests
=> DLP: Added sample for Deidentify data using redact

dlp/api/Snippets.Tests/DeidentifyWithReplacementTests.cs, dlp/api/Snippets/DeidentifyWithReplacement.cs
- Added sample for [Deidentify content using replace config](https://cloud.google.com/dlp/docs/deidentify-sensitive-data.md#dlp_deidentify_replace-java) and unit tests
=> DLP: Added sample for deidentifying content with replacement

dlp/api/Snippets.Tests/DeidentifyTableWithRowSuppressTests.cs, dlp/api/Snippets/DeidentifyTableWithRowSuppress.cs
- Added sample for [Deidentify Table With Row Suppress](https://cloud.google.com/dlp/docs/examples-deid-tables.md#suppress_a_row_based_on_the_content_of_a_column) and unit tests.
=> DLP: Added sample for deidentify table with row suppress

dlp/api/Snippets.Tests/DeidentifyUsingTableBucketingTests.cs, dlp/api/Snippets/DeidentifyUsingTableBucketing.cs
-  Added sample for [Deidentify Table Data Using Fixed Bucketing](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_a_column_without_inspection) and unit tests.
=> DLP: Added sample for deidentify table data using fixed bucketing

dlp/api/Snippets.Tests/DeidentifyTableUsingLogicInfoTypesTests.cs, dlp/api/Snippets/DeidentifyTableUsingLogicInfoTypes.cs
- Added sample for [Deidentify Table Using Condition and Infotypes](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_findings_only_when_specific_conditions_are_met_on_another_field) and unit tests
=> DLP: Added sample for deidentify table using condition and infotypes

dlp/api/Snippets.Tests/InspectDataWithHotwordRuleTests.cs, dlp/api/Snippets/InspectDataWithHotwordRule.cs
- Added sample for [Inspect data with hotword rule](https://cloud.google.com/dlp/docs/creating-custom-infotypes-likelihood.md#match-mrn) and unit tests.
=> DLP: Added sample for inspecting data with hotword rule

dlp/api/Snippets.Tests/InspectImagesForSensitiveDataWithInfoTypesTests.cs, dlp/api/Snippets/InspectImageForSensitiveDataWithInfoTypes.cs
- Added sample for [Inspect Image With All Infotypes](https://cloud.google.com/dlp/docs/inspecting-images.md#dlp-inspect-image-all-infotypes-java) with test cases
=> DLP: Added sample for inspect image with all infotypes

.github/renovate.json
- Configure renovate bot PRs to have the `automerge: exact` label.
- Stop ignoring the App Engine Flex samples for dependency renovation as they are being updated.
=> chore: Improve renovate bot configuration.

dlp/api/Snippets.Tests/DeidentifyDataUsingDictionaryReplacementTests.cs, dlp/api/Snippets/DeidentifyDataUsingDictionaryReplacement.cs
- Added sample for [Deidentify Data Using Dictionary Replacements](https://cloud.google.com/dlp/docs/transformations-reference#dictionary-replacement) and test cases
=> DLP: Added sample for deidentify data using dictionary replacements

dlp/api/Snippets.Tests/DeidentifyWithReplaceInfotypesTests.cs, dlp/api/Snippets.Tests/runTest.ps1, dlp/api/Snippets/DeidentifyWithReplaceInfotypes.cs
- Added sample for [Deidentify Data With Replace Infotypes](https://cloud.google.com/dlp/docs/redacting-sensitive-data.md#dlp-replace-infotype-java) and test cases
=> DLP: Added sample for deidentify data with replace infotypes

dlp/api/Snippets.Tests/RedactImageWithListedInfotypesTests.cs, dlp/api/Snippets/RedactImageWithListedInfotypes.cs
- Updated the region tag to `dlp_redact_image_listed_infotypes` from `redact_image` and renamed the files.
=> DLP: Fixed the region tag of redact image with listed infoTypes

firestore/api/FirestoreTest/FirestoreTest.cs, firestore/api/ListenData/Program.cs
Increase delay in listener tests from 1sec to 3 sec and un-skip flaky listeners tests.
=> fix: firestore flaky test issue#1162

pubsub/api/Pubsub.Samples.Tests/PubsubFixture.cs
Add console statements to catch the reason when disposal fail  in pubsub samples test fixture.
=> chore: Add console statements to catch the reason when disposal fail

.editorconfig, Directory.Build.props
To support consistent styling across the samples, there are two files in this PR:
1.  .editorconfig - This is very similar to the [.editorconfig used in google-cloud-dotnet](https://github.com/googleapis/google-cloud-dotnet/blob/main/.editorconfig). This one however has rules for public, internal and  private method names, properties etc and the list of common diagnostic listed at the bottom with the  severity set to suggestion. When all the current violations are fixed, we can change the severity of important diagnostics to warning/errors as needed.
2.  Directory.Build.Props - By adding a new property to this file placed in the root folder of the source, the property is added to every project in the subfolders. This can be used to enforce the code style in build using …
=> feat: Add support for editorconfig

endpoints/getting-started/src/IO.Swagger/app.yaml
Region tag 'configuration' no longer used as of cl/536428490
=> chore(endpoints): Remove deprecated region tag

dlp/api/Snippets.Tests/DeidentifyFreeTextWithFpeUsingSurrogateTests.cs, dlp/api/Snippets/DeidentifyFreeTextWithFpeUsingSurrogate.cs
- Added sample for [Deidentify Free Text With FPE Using Surrogate](https://cloud.google.com/dlp/docs/samples/dlp-deidentify-free-text-with-fpe-using-surrogate) and test cases
=> DLP: Added sample for deidentify free text using surrogate with fpe

dlp/api/Snippets.Tests/ReidentifyFreeTextWithFpeUsingSurrogateTests.cs, dlp/api/Snippets/ReidentifyFreeTextWithFpeUsingSurrogate.cs
- Added sample for [Reidentify Free Text With FPE Using a Surrogate](https://cloud.google.com/dlp/docs/samples/dlp-deidentify-free-text-with-fpe-using-surrogate) and test cases
=> DLP: Added sample for reidentify free text with fpe using surrogate

.github/renovate.json
The label is removed within 6 hours and because of the time zone distribution of the team this is not enough. Also, the automerge bot seems to be rebasing on top of main when there's one LGTM, which then conflicts with renovate tryingt to rebase the PR as there's a commit it doesn't recognize.
=> Don't use merge:exact on the renovate PRs

securitycenter/api/src/CreateNotificationConfigSnippets.g.cs, securitycenter/api/src/DeleteNotificationConfigSnippets.g.cs, securitycenter/api/src/GetNotificationConfigSnippets.g.cs, securitycenter/api/src/ListNotificationConfigSnippets.g.cs, securitycenter/api/src/UpdateNotificationConfigSnippets.g.cs
Contains only comment updates to allow new parent types (b/263299056)
=> docs(scc-samples): update comments to add new parent resource types

media/stitcher/api/Stitcher.Samples.Tests/CreateCdnKeyAkamaiAsyncTests.cs, media/stitcher/api/Stitcher.Samples.Tests/CreateCdnKeyAsyncTests.cs, media/stitcher/api/Stitcher.Samples.Tests/CreateLiveConfigAsyncTests.cs, media/stitcher/api/Stitcher.Samples.Tests/CreateSlateAsyncTests.cs, media/stitcher/api/Stitcher.Samples.Tests/DeleteCdnKeyAsyncTests.cs, media/stitcher/api/Stitcher.Samples.Tests/DeleteLiveConfigAsyncTests.cs, media/stitcher/api/Stitcher.Samples.Tests/DeleteSlateAsyncTests.cs, media/stitcher/api/Stitcher.Samples.Tests/GetLiveAdTagDetailTests.cs, media/stitcher/api/Stitcher.Samples.Tests/GetLiveConfigTests.cs, media/stitcher/api/Stitcher.Samples.Tests/GetLiveSessionTests.cs, media/stitcher/api/Stitcher.Samples.Tests/ListLiveAdTagDetailsTests.cs, media/stitcher/api/Stitcher.Samples.Tests/ListLiveConfigsTests.cs, media/stitcher/api/Stitcher.Samples.Tests/StitcherFixture.cs, media/stitcher/api/Stitcher.Samples.Tests/UpdateCdnKeyAkamaiTests.cs, media/stitcher/api/Stitcher.Samples.Tests/UpdateCdnKeyAsyncTests.cs, media/stitcher/api/Stitcher.Samples.Tests/UpdateSlateAsyncTests.cs, media/stitcher/api/Stitcher.Samples/CreateCdnKeyAkamaiAsync.cs, media/stitcher/api/Stitcher.Samples/CreateCdnKeyAsync.cs, media/stitcher/api/Stitcher.Samples/CreateLiveConfigAsync.cs, media/stitcher/api/Stitcher.Samples/CreateSlateAsync.cs, media/stitcher/api/Stitcher.Samples/DeleteCdnKeyAsync.cs, media/stitcher/api/Stitcher.Samples/DeleteLiveConfigAsync.cs, media/stitcher/api/Stitcher.Samples/DeleteSlateAsync.cs, media/stitcher/api/Stitcher.Samples/GetLiveConfig.cs, media/stitcher/api/Stitcher.Samples/ListLiveConfigs.cs, media/stitcher/api/Stitcher.Samples/Stitcher.Samples.csproj, media/stitcher/api/Stitcher.Samples/UpdateCdnKeyAkamaiAsync.cs, media/stitcher/api/Stitcher.Samples/UpdateCdnKeyAsync.cs, media/stitcher/api/Stitcher.Samples/UpdateSlateAsync.cs, media/stitcher/api/runTests.ps1
Create/delete/update methods on slates and CDN keys are now LROs.
Added live config methods (create/delete/get/list but no update) and tests.
Creating a live session now requires a live config.
Creating a VOD session now requires the `AdTracking` field.
Fixes #2100
=> fix(Video Stitcher): broken tests due to API changes

dlp/api/Snippets.Tests/InspectTableWithCustomHotwordsTests.cs, dlp/api/Snippets/InspectTableWithCustomHotwords.cs
- Added sample for [Inspect Table with Custom Hotwords](https://cloud.google.com/dlp/docs/creating-custom-infotypes-likelihood.md#match-column-values) and unit tests
=> DLP: Added sample for Inspect table with custom hotwords

dlp/api/Snippets.Tests/DeidentifyWithDeterministicTests.cs, dlp/api/Snippets.Tests/ReidenitifyContentUsingDeterministicTests.cs, dlp/api/Snippets/DeidentifyWithDeterministic.cs, dlp/api/Snippets/ReidentifyContentUsingDeterministic.cs
- Added sample for [De-identify content through deterministic encryption](https://cloud.google.com/dlp/docs/samples/dlp-deidentify-deterministic) and [Re-identify content encrypted by deterministic encryption](https://cloud.google.com/dlp/docs/samples/dlp-reidentify-deterministic) and unit tests
=> DLP: Added sample for Deidentify and Reidentify content using deterministic

storage/api/Storage.Samples.Tests/GenerateV4ReadSignedUrlTest.cs, storage/api/Storage.Samples.Tests/GenerateV4UploadSignedUrlTest.cs, storage/api/Storage.Samples/GenerateV4ReadSignedUrl.cs, storage/api/Storage.Samples/GenerateV4UploadSignedUrl.cs
updated GenerateV4SignedReadUrlSample and GenerateV4UploadSignedUrlSample to use UrlSigner.FromCredentialFile(credentialFilePath) instead of the deprecated UrlSigner.FromServiceAccountPath(credentialFilePath).
=> chore: Update gcs samples

dlp/api/Snippets.Tests/CreateStoredInfoTypesTests.cs, dlp/api/Snippets.Tests/InspectDataWithStoredInfotypesTests.cs, dlp/api/Snippets.Tests/UpdateStoredInfoTypesTests.cs, dlp/api/Snippets/CreateStoredInfoTypes.cs, dlp/api/Snippets/InspectDataWithStoredInfotypes.cs, dlp/api/Snippets/UpdateStoredInfoTypes.cs
- Added sample for [Create a stored infoType](https://cloud.google.com/dlp/docs/creating-stored-infotypes#create-storedinfotye), [Update a stored infoType](https://cloud.google.com/dlp/docs/creating-stored-infotypes#rebuild) and [Inspect Data with stored infoType](https://cloud.google.com/dlp/docs/creating-stored-infotypes#scan-with-large-custom-infotype) and unit tests
=> DLP: Added sample for create, update and inspect with stored infoTypes

dlp/api/Snippets.Tests/ReidentifyFreeTextFpeTests.cs, dlp/api/Snippets/ReidentifyFreeTextFpe.cs
- Added sample for [Reidentify Free Text Using FPE](https://cloud.google.com/dlp/docs/samples/dlp-reidentify-text-fpe) and unit tests
=> DLP: Added sample for reidentify free text using FPE and test cases

dlp/api/Snippets.Tests/InspectDataStoreJobWithSCCIntegrationTests.cs, dlp/api/Snippets/InspectDataStoreJobWithSCCIntegration.cs
- Added sample for [Inspect Datastore Job With SCC Integration](https://cloud.google.com/dlp/docs/sending-results-to-scc.md?g=0&l=416#datastore-data) and unit test cases
=> DLP: Added sample for Inspect Datastore Job with SCC integration

dlp/api/Snippets.Tests/InspectDataUsingAugmentInfoTypesTests.cs, dlp/api/Snippets/InspectDataUsingAugmentInfoTypes.cs
- Added sample for [Inspect Data Using Augment InfoType](https://cloud.google.com/dlp/docs/creating-custom-infotypes-dictionary#augment_a_built-in_infotype_detector) and unit test cases
=> DLP: Added sample for inspect data using augment infotype

error-reporting/api/ErrorReportingSample/ErrorReportingSample.cs
this is a refactoring of the change made in #2329 .
it removes the explicit source location as [recommended] by Error Reporting API. align the method name to the language guidelines.
[recommended]: https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report#ReportedErrorEvent.FIELDS.message
=> chore: refactor error reporting sample

spanner/api/Spanner.Samples/CustomTimeoutsAndRetriesAsync.cs
Fixes a couple of minor issues in the retry- and timeout sample:
1. Remove `DeadlineExceeded` as a retryable code, as the sample uses a single timeout will not retry on `DeadlineExceeded` anyways, meaning that the addition of that error code was just confusing.
2. Update the `maxBackoff` to 16 seconds. It was currently 6400ms, which was a typo, as all the other client libraries used 64s. That was also the value that was mentioned in the documentation page that imports this sample, meaning that there was a discrepancy between the documentation and the sample. We are setting this value to 16 seconds for all client libraries, as it makes the sample confusing when the max backoff is larger than the total timeout (60 seconds).
The documentation page that uses this sample is …
=> docs: update custom retry and timeout sample

dlp/api/Snippets/DeidentifyTableWithPrimitiveBucketing.cs
- Fixed region tag typo to `dlp_deidentify_table_primitive_bucketing`.
=> DLP: Fixed region tag typo

pubsub/api/Pubsub.Samples.Tests/CreateBigQuerySubscriptionTest.cs, pubsub/api/Pubsub.Samples.Tests/CreateCloudStorageSubscriptionTest.cs, pubsub/api/Pubsub.Samples.Tests/CreatePushSubscriptionTest.cs, pubsub/api/Pubsub.Samples.Tests/PubsubFixture.cs, pubsub/api/Pubsub.Samples.Tests/UpdatePushConfigurationTest.cs, pubsub/api/Pubsub.Samples/CreateBigQuerySubscription.cs, pubsub/api/Pubsub.Samples/CreateCloudStorageSubscription.cs
First commit is just tidy-up.
Currently the test fails due to permissions ("Cloud Pub/Sub did not have the necessary permissions configured to access the provided bucket [...]") - but so does the BigQuery test (in a different way).
I thought I'd create the PR to get feedback on whether this is the right approach and I should add an IAM call to grant permission for the Pub/Sub service account to the bucket, or something else.
=> docs(pubsub): Add CreateCloudStorageSubscription sample

dlp/api/Snippets.Tests/InspectImagesForSensitiveDataWithInfoTypesTests.cs, dlp/api/Snippets.Tests/runTest.ps1, dlp/api/Snippets/InspectImageForSensitiveDataWithInfoTypes.cs
Test as written was somewhat flaky, verifying only on the number of findings. Location detector gave an unlikely but valid additional finding which increased the response finding count. 
Fixed by setting specific InfoTypes to search for (thus ignoring unlikely fringe findings) and updating test assertions.
=> Fix failing InspectImage test from issue #2511

spanner/api/QuickStart/QuickStart.csproj, spanner/api/Spanner.Samples.Tests/CommitDelayAsyncTest.cs, spanner/api/Spanner.Samples.Tests/DirectedReadsAsyncTest.cs, spanner/api/Spanner.Samples.Tests/Spanner.Samples.Tests.csproj, spanner/api/Spanner.Samples.Tests/TransactionTagAsyncTest.cs, spanner/api/Spanner.Samples/CommitDelayAsync.cs, spanner/api/Spanner.Samples/DirectedReadsAsync.cs, spanner/api/Spanner.Samples/QueryDataWithTransactionAsync.cs, spanner/api/Spanner.Samples/Spanner.Samples.csproj, spanner/api/Spanner.Samples/TransactionTagAsync.cs
Tests won't pass until https://github.com/googleapis/google-cloud-dotnet/pull/12164 is merged and release. I'm currently running them locally.
=> feat[Spanner]: Add samples for new features

spanner/api/Spanner.Samples.Tests/UpdateUsingDmlReturningAsyncTest.cs
- We had an `async void` inserting data that we needed for the test. The data was not always available when needed.
- Also, simplified the tests.
- I searched for others `async void`, there are none.
=> tests[Spanner]: Fix flake in UpdateUsingDmlReturningAsyncTest

storage/api/Storage.Samples.Tests/StorageControlQuickstartTest.cs, storage/api/Storage.Samples/Storage.Samples.csproj, storage/api/Storage.Samples/StorageControlQuickstart.cs
Adds a quickstart sample for storage control
=> feat(storage): add quickstart sample for storage control

aiplatform/api/AIPlatform.Samples.Tests/GroundingWebTest.cs, aiplatform/api/AIPlatform.Samples/GroundingVertexAiSearchSample.cs, aiplatform/api/AIPlatform.Samples/GroundingWebSample.cs
Note: I didn't add `GroundingVertexAiSearchTest` because `GroundingVertexAiSearchSample` requires a data store to be setup and running. I didn't think this was appropriate for unit tests.
=> docs(aiplatform): Add GroundingWebSample.cs and GroundingVertexAiSearchSample.cs #2624

storageinsights/api/StorageInsights.Samples.Tests/CreateInventoryReportConfigTest.cs, storageinsights/api/StorageInsights.Samples.Tests/DeleteInventoryReportConfigTest.cs, storageinsights/api/StorageInsights.Samples.Tests/EditInventoryReportConfigTest.cs, storageinsights/api/StorageInsights.Samples.Tests/GetInventoryReportNamesTest.cs, storageinsights/api/StorageInsights.Samples.Tests/ListInventoryReportConfigsTest.cs, storageinsights/api/StorageInsights.Samples.Tests/StorageFixture.cs, storageinsights/api/StorageInsights.Samples.Tests/StorageInsights.Samples.Tests.csproj, storageinsights/api/StorageInsights.Samples/CreateInventoryReportConfig.cs, storageinsights/api/StorageInsights.Samples/DeleteInventoryReportConfig.cs, storageinsights/api/StorageInsights.Samples/EditInventoryReportConfig.cs, storageinsights/api/StorageInsights.Samples/GetInventoryReportNames.cs, storageinsights/api/StorageInsights.Samples/ListInventoryReportConfigs.cs, storageinsights/api/StorageInsights.Samples/StorageInsights.Samples.csproj, storageinsights/api/StorageInsights.sln, storageinsights/api/runTests.ps1
Adds samples for storage insights, and tests
Fixes https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/2287
=> feat(storageinsights): Adds samples for storage insights

functions/concepts/EnvironmentVariables/Function.cs, functions/concepts/ExecutionCount/Function.cs, functions/concepts/FileSystem/Function.cs, functions/concepts/LazyFields/Function.cs, functions/concepts/Scopes/Function.cs, functions/firebase/FirestoreReactive/Function.cs, functions/helloworld/HelloHttp/Function.cs, functions/helloworld/HelloWorld/Function.cs, functions/http/Cors/Function.cs, functions/http/HttpFormData/Function.cs, functions/http/HttpRequestMethod/Function.cs, functions/http/ParseContentType/Function.cs, functions/http/SendHttpRequest/Function.cs, functions/logging/LogHelloWorld/Function.cs, functions/responsestreaming/StreamBigQuery/Function.cs, functions/slack/SlackKnowledgeGraphSearch/Function.cs
There are a few samples that use StreamReader or TextReader to read the request, and ReadLineAsync / ReadToEndAsync don't accept cancellation tokens in .NET 6; we should update those if and when we update the samples to .NET 8.
=> feat: Use an appropriate CancellationToken in all Functions Frameworks samples

aiplatform/api/AIPlatform.Samples.Tests/AIPlatform.Samples.Tests.csproj, aiplatform/api/AIPlatform.Samples/AIPlatform.Samples.csproj, aiplatform/api/AIPlatform.sln
This is so the test script can pick up the projects to restore and run tests from.
Also, upgrading to .NET 8
=> ci: Add AIPlatform projects to the existing solution

.github/renovate.json
For these, we need to confirm that the environments they are meant for support .NET 8 and documentation needs to be updated also.
=> chore: Stop automatic upgrade of some samples to .NET 8

functions/responsestreaming/StreamBigQuery.Tests/StreamBigQuery.Tests.csproj
This will be upgraded to .NET 8 in #2729 but there are still some documentation aspects that need to be cleared out before that can be merged.
And this sample has been failing since we updated CI to support .NET 6 and .NET 8 only.
=> build[Functions]: Make ResponseStreaming test target .NET 6

aiplatform/api/AIPlatform.Samples/GeminiQuickstart.cs, aiplatform/api/AIPlatform.Samples/PredictChatPromptSample.cs, aiplatform/api/AIPlatform.Samples/PredictTextPrompt.cs
No code changes. 
Adding `generativeaionvertexai_` region tags to replace old `aiplatform_`
In near future GenAI code samples, will only use `generativeaionvertexai_` region tag prefix.
=> docs(generativeai): add region tags for code samples

aiplatform/api/AIPlatform.Samples/GeminiQuickstart.cs, aiplatform/api/AIPlatform.Samples/MultiTurnChatSample.cs, aiplatform/api/AIPlatform.Samples/MultimodalMultiImage.cs, aiplatform/api/AIPlatform.Samples/MultimodalVideoInput.cs, aiplatform/api/AIPlatform.Samples/WithSafetySettings.cs
Adding `generativeaionvertexai_` region tags to replace old `aiplatform_`
In near future GenAI code samples, will only use `generativeaionvertexai_` region tag prefix.
=> chore: cleanup unused region tags

spanner/api/Spanner.Samples.Tests/Spanner.Samples.Tests.csproj, spanner/api/Spanner.Samples/Spanner.Samples.csproj
Assuming we want the samples to refer to GA library versions, we won't be able to update the dependency until 5.0.0 has been released.
=> chore: Revert to Google.Cloud.Spanner.Data version 5.0.0-beta03

spanner/api/Spanner.Samples/BatchReadRecordsAsync.cs, spanner/api/Spanner.Samples/QueryDataWithTransactionAsync.cs, spanner/api/Spanner.Samples/QueryDataWithTransactionCoreAsync.cs, spanner/api/Spanner.Samples/ReadStaleDataAsync.cs, spanner/api/Spanner.Samples/Spanner.Samples.csproj
This PR upgrades google.cloud.spanner.data to v5.0.0-beta04 dependency and fixes the broken samples.
=> chore(deps): update dependency google.cloud.spanner.data to v5.0.0-beta04

spanner/api/Spanner.Samples.Tests/CreateFullBackupScheduleTest.cs, spanner/api/Spanner.Samples.Tests/CreateIncrementalBackupScheduleTest.cs, spanner/api/Spanner.Samples.Tests/DeleteBackupScheduleTest.cs, spanner/api/Spanner.Samples.Tests/GetBackupScheduleTest.cs, spanner/api/Spanner.Samples.Tests/ListBackupSchedulesTest.cs, spanner/api/Spanner.Samples.Tests/UpdateBackupScheduleTest.cs, spanner/api/Spanner.Samples/CreateFullBackupSchedule.cs, spanner/api/Spanner.Samples/CreateIncrementalBackupSchedule.cs, spanner/api/Spanner.Samples/DeleteBackupSchedule.cs, spanner/api/Spanner.Samples/GetBackupSchedule.cs, spanner/api/Spanner.Samples/ListBackupSchedules.cs, spanner/api/Spanner.Samples/UpdateBackupSchedule.cs
This PR adds code samples for the following APIs:
1. CreateBackupSchedule (both full and incremental backup schedules)
2. ListBackupSchedules
3. GetBackupSchedule
4. UpdateBackupSchedule
5. DeleteBackupSchedule
=> feat(Spanner): Add samples for Cloud Spanner Scheduled Backups

.github/blunderbuss.yml, CODEOWNERS
* Add secrets manager team to the `secretmanager/` code-owners in _CODEOWNERS_ file
* Need access to the secrets-manager team to be able to review and partake in the review process.
=> Add secrets team to codeowners

.github/blunderbuss.yml, CODEOWNERS
Cloud SQL samples ownership has moved from Cloud SDK back to Cloud SQL and as such the `infra-db-sdk` team should instead be `cloud-sql-connectors`
Will need someone to give write access to @GoogleCloudPlatform/cloud-sql-connectors on this repo for the CODEOWNERS file to be happy
=> chore: Update CODEOWNERS and blunderbuss config

iam/api/QuickStart/QuickStart.cs
Includes changing "member" to "principal" and linking to principal identifiers page instead of specifying recommended format.
I left "member" when it referred to the field in the role binding, since that field is still called "members."
Please **merge** this PR for me once it is approved
=> docs(iam): Update QuickStart.cs comments

run/pubsub/Run.Samples.Pubsub.MinimalApi/Dockerfile
Migrate region "cloudrun_pubsub_dockerfile" to "cloudrun_pubsub_dockerfile_csharp" in order to align with pattern "product_regiontag_typeoffile_language" and create a consistency between languages.
Fixes [b/393606199](http://b/393606199)
=> chore(cloudrun): migrate region "cloudrun_pubsub_dockerfile" at run/pubsub/Run.Samples.Pubsub.MinimalApi/Dockerfile

run/pubsub/Run.Samples.Pubsub.MinimalApi/Dockerfile
Delete old region tag "cloudrun_pubsub_dockerfile" from run/pubsub/Run.Samples.Pubsub.MinimalApi/Dockerfile
Fixes [b/393606199](http://b/393606199)
=> chore(cloudrun): delete old region tag "cloudrun_pubsub_dockerfile"

.github/blunderbuss.yml, CODEOWNERS, parametermanager/README.md
feat(parametermanager): created folder to add samples
Added a placeholder file for folder creation of parametermanager
Added cloud-parameters-team to blunderbuss.yml and CODEOWNERS
=> feat(parametermanager): created folder to add samples

secretmanager/api/SecretManager.Samples.Tests/CreateSecretWithDelayedDestroyTests.cs, secretmanager/api/SecretManager.Samples.Tests/DestroySecretVersionTests.cs, secretmanager/api/SecretManager.Samples.Tests/DisableSecretDelayedDestroyTests.cs, secretmanager/api/SecretManager.Samples.Tests/DisableSecretVersionTests.cs, secretmanager/api/SecretManager.Samples.Tests/EnableSecretVersionTests.cs, secretmanager/api/SecretManager.Samples.Tests/SecretManagerFixture.cs, secretmanager/api/SecretManager.Samples.Tests/UpdateSecretWithDelayedDestroyTests.cs, secretmanager/api/SecretManager.Samples/CreateSecretWithDelayedDestroy.cs, secretmanager/api/SecretManager.Samples/DisableSecretDelayedDestroy.cs, secretmanager/api/SecretManager.Samples/UpdateSecretWithDelayedDestroy.cs
- Added the necessary code samples for Delayed Destroy
- Added the test files for the code samples added
- Added the required changes in the fixture file
- Refactored some test cases file that were modified.
- PS: The test cases added served as service functionality and were removed, but kept the refactoring introduced to the test files to adhere to the best practices.
- https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/2984
closes: #<2984>
=> chore(secretmanager): Add global samples for delayed destroy

pubsub/api/Pubsub.Samples.Tests/PubsubFixture.cs
https://cloud.google.com/pubsub/docs/samples/pubsub-create-topic-with-aws-msk-ingestion
https://cloud.google.com/pubsub/docs/samples/pubsub-create-topic-with-azure-event-hubs-ingestion
https://cloud.google.com/pubsub/docs/samples/pubsub-create-topic-with-confluent-cloud-ingestion
=> feat(PubSub): Add methods to generate random ingestion params for samples

pubsub/api/Pubsub.Samples.Tests/CreateTopicWithKinesisIngestionTest.cs, pubsub/api/Pubsub.Samples/CreateTopicWithKinesisIngestion.cs
https://cloud.google.com/pubsub/docs/samples/pubsub-create-topic-with-kinesis-ingestion
PubSub Fixture has a separate PR that this sample depends on: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/3030
=> feat(PubSub): Add CreateTopicWithKinesisIngestion Sample

pubsub/api/Pubsub.Samples.Tests/CreateAvroSchemaTest.cs, pubsub/api/Pubsub.Samples.Tests/CreateProtoSchemaTest.cs
bug: https://b.corp.google.com/issues/214289281
We think what's happening is that the CreateSchema operation would rarely return a transient error after the schema is created, which causes a retry at library level and lead to an AlreadyExists exception. This results in our sample to return the schema object without the revision parameters, causing the assert.equal to fail. I confirmed with PubSub team that this is an expected behavior and no change is required on the library.
To address the flakiness on these tests, we removed the Get call from our tests and modified the assertion to check the SchemaName of the created schema instead.
=> fix(PubSub): Fix flakiness on CreateSchema tests

secretmanager/api/SecretManager.Samples.Tests/AccessSecretVersionTests.cs, secretmanager/api/SecretManager.Samples.Tests/AddSecretVersionTests.cs, secretmanager/api/SecretManager.Samples.Tests/CreateSecretTests.cs, secretmanager/api/SecretManager.Samples.Tests/CreateSecretWithAnnotationsTests.cs, secretmanager/api/SecretManager.Samples.Tests/CreateSecretWithLabelsTests.cs, secretmanager/api/SecretManager.Samples.Tests/CreateUserManagedReplicationSecretTests.cs, secretmanager/api/SecretManager.Samples.Tests/DeleteSecretTests.cs, secretmanager/api/SecretManager.Samples.Tests/EditSecretAnnotationsTests.cs, secretmanager/api/SecretManager.Samples.Tests/QuickstartTests.cs, secretmanager/api/SecretManager.Samples.Tests/SecretManagerFixture.cs, secretmanager/api/SecretManager.Samples.Tests/UpdateSecretTests.cs, secretmanager/api/SecretManager.Samples.Tests/UpdateSecretWithAliasTests.cs, secretmanager/api/SecretManager.Samples.Tests/ViewSecretAnnotationsTests.cs, secretmanager/api/SecretManager.Samples.Tests/ViewSecretLabelsTests.cs, secretmanager/api/SecretManager.Samples/CreateSecretWithAnnotations.cs, secretmanager/api/SecretManager.Samples/CreateSecretWithLabels.cs, secretmanager/api/SecretManager.Samples/EditSecretAnnotations.cs, secretmanager/api/SecretManager.Samples/ViewSecretAnnotations.cs, secretmanager/api/SecretManager.Samples/ViewSecretLabels.cs
- Added the necessary code samples for labels
- Added the necessary code samples for annotations
- Added the test files for the code samples added
- Fixed the formatting issue
- Add the required changes in the fixture file
- Fixed the flaky suite issue by having individual secret(resource) for each test.
- Verified the behaviour of the changes with tests
- Verified the behaviour of the changes locally.
- https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/3102
closes: #<3102>
=> [SecretManager][Samples]: Add global samples for label & annotation / Fix TestSuite Flakiness
