GoogleCloudPlatform/dotnet-docs-samples

- bigquery/api/BigQueryUtil/BigQueryUtil.csproj
- bigquery/api/BigQueryUtil/BigQueryUtil.sln
- bigquery/api/BigQueryUtil/Properties/AssemblyInfo.cs
- bigquery/api/BigQueryUtil/Util.cs
- bigquery/api/BigQueryUtil/app.config
- bigquery/api/BigQueryUtil/packages.config
- bigquery/api/BigQueryUtil/test/Properties/AssemblyInfo.cs
- bigquery/api/BigQueryUtil/test/Test.cs
- bigquery/api/BigQueryUtil/test/app.config
- bigquery/api/BigQueryUtil/test/packages.config
- bigquery/api/BigQueryUtil/test/test.csproj
- bigquery/api/GettingStarted/Program.cs
Code for 4 pages under cloud.google.com/bigquery/...
Also, change the GettingStarted sample to use the synchronous interface,
because it's simpler.
> BigQueryUtil samples with tests.

- .gitignore
- storage/api/Program.cs
- storage/api/test/Test.cs
https://cloud.google.com/storage/docs/json_api/v1/json-api-dotnet-samples
Discusses Installed Application Credentials, so we need to show it in the
code.
> Show how to use Installed Application Credentials too.

- storage/powershell/Copy-GcsObject.ps1
The offending bug has been fixed.
https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/17
> Drop current directory sync code.

- storage/powershell/Copy-GcsObject.ps1
- storage/powershell/Pester.Tests.ps1
Follow the convention used by hadoop and other tools.
Also, make the test more resilient to semantically meaningless changes
by sorting the output before comparing.
> Use _$folder$ suffix instead of / suffix to tag directories.

- storage/api/packages.config
- storage/api/storage.csproj
- storage/api/test/packages.config
- storage/api/test/test.csproj
In a desperate, misguided attempt to fix
https://github.com/google/google-api-dotnet-client/issues/775
> Update Google packages to latest.

- datastore/api/DatastoreTest.cs
'type' could cause confusion with data type.
> Uses 'category' instead of 'type' as a property name

- bigquery/api/GettingStarted/Program.cs
The sample Program.cs file was inadvertently excluded from the previous pull request. This PR is to include it.
> Bigquery update to include Program.cs

- language/api/Analyze/AnalyzeTest/AnalyzeTest.cs
The speech API results have change polarity.
> Fix speech sentiment test.

- storage/api-veneer/QuickStart/Program.cs
- storage/api-veneer/QuickStartTest/QuickStartTest.cs
I refactored a lot of the test code so that the test bucket is
automatically cleaned up at the end of the test.
Also, tests were flaky because there was some kind of race condition
around Console.Out.  So, I changed the code so that you pass Console.Out
to Main().  No more race condition.
> More storage samples with tests.  Still not complete.

- pubsub/api/PubsubTest.csproj
- pubsub/api/app.config
- pubsub/api/packages.config
I was getting mysterious auth errors with the old packages.
> Update Google.Pubsub.V1 to latest version.

- bigquery/api/GettingStarted/BigqueryTest/BigqueryTest.cs
Update to restore END region tag for async_query region
> Update END region tag

- datastore/api/TaskListTest/DatastoreTest.cs
- datastore/api/runTests.ps1
They should expect and cope with eventual consistency.
> Fix flaky datastore tests.

- BuildTools.psm1
- storage/api-veneer/runTests.ps1
The new function edits text files during the build, and restores them when
the build completes.  We had copied and pasted the code a couple places.
We can update those locations to use the new functions.
> Add build function BackupAndEdit-TextFile.

- storage/api-veneer/QuickStart/Program.cs
- storage/api-veneer/QuickStartTest/QuickStartTest.cs
Tests were failing, even with a 2-second delay before calling list.  2
seconds is not long enough.  So, use Eventually() to give assertions
more than 10 seconds to become true, but not delay when the assertion
succeeds immedately.  And explicitly track every file that must be deleted
at the end of a test instead of listing them.
> Fix flaky tests with true deterministic clean up.

- language/api/Analyze/AnalyzeTest/AnalyzeTest.cs
- language/api/Analyze/Program.cs
> Command and tests that read text from files.

- BuildTools.psm1
BigQuery annoyingly exceeds 3 minutes every day or two.
> Increase test timout from 3 to 5 minutes.

- storage/api/QuickStart/Program.cs
- storage/api/QuickStartTest/QuickStartTest.cs
- storage/api/QuickStartTest/QuickStartTest.csproj
- storage/api/QuickStartTest/packages.config
Also, use TestUtil.cs and remove redundant code.
> Retry transient errors seen in CI tests.

- logging/api/LoggingTest/LoggingTest.cs
Saw two automated tests fail over the weekend due to this issue.
> Retry when the API returns a flaky response code.

- bigquery/api/GettingStarted/runTests.ps1
In an attempt to make the BigQuery test less flaky.
> Run BigQuery tests one at a time, not in parallel.

- BuildTools.psm1
In an attempt to make the whole test suite run faster.
> Run tests in parallel.

- BuildTools.psm1
This reverts commit 8799c5e314042af22c0ea4c227d9b24cedebef3b.
See issue
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/116
> Revert "Run tests in parallel."

- BuildTools.psm1
Still seeing automated test fail once per day.  This should reduce the failure rate to less than once per day, I hope.
> When a test script fails, retry once.

- BuildTools.psm1
I accidentally dropped the code that prints the list of tests
in the prior change.
> List the tests that succeeded, failed, etc.

- speech/api/QuickStart/App.config
- speech/api/QuickStart/Properties/AssemblyInfo.cs
- speech/api/QuickStart/QuickStart.cs
- speech/api/QuickStart/QuickStart.csproj
- speech/api/QuickStart/packages.config
- speech/api/Recognize/App.config
- speech/api/Recognize/Properties/AssemblyInfo.cs
- speech/api/Recognize/Recognize.cs
- speech/api/Recognize/Recognize.csproj
- speech/api/Recognize/packages.config
- speech/api/Speech.sln
- speech/api/SpeechTest/Properties/AssemblyInfo.cs
- speech/api/SpeechTest/SpeechTest.cs
- speech/api/SpeechTest/SpeechTest.csproj
- speech/api/SpeechTest/app.config
- speech/api/SpeechTest/packages.config
- speech/api/runTests.ps1
The API doesn't yet support streaming, so those samples are missing.
> Speech recognize sample.

- speech/api/Recognize/Recognize.cs
- speech/api/Recognize/Recognize.csproj
- speech/api/Recognize/packages.config
- speech/api/SpeechTest/SpeechTest.cs
This reverts commit f78684c02f89562366b47a9bc72a0717ee891ec6.
> Revert "Streaming samples."

- speech/api/Recognize/Recognize.cs
- speech/api/Recognize/Recognize.csproj
- speech/api/Recognize/packages.config
- speech/api/SpeechTest/SpeechTest.cs
Skip streaming test until bug is resolved.
> Resurrect streaming speech.

- appengine/flexible/AppEngineFlex.sln
- appengine/flexible/CloudSql/CloudSql.xproj
- appengine/flexible/CloudSql/CloudSql.xproj.user
- appengine/flexible/CloudSql/Dockerfile
- appengine/flexible/CloudSql/Program.cs
- appengine/flexible/CloudSql/Properties/launchSettings.json
- appengine/flexible/CloudSql/Startup.cs
- appengine/flexible/CloudSql/app.yaml
- appengine/flexible/CloudSql/appsettings.json
- appengine/flexible/CloudSql/deployTests.ps1
- appengine/flexible/CloudSql/project.json
- appengine/flexible/CloudSql/project.lock.json
- appengine/flexible/CloudSql/runTests.ps1
- appengine/flexible/CloudSql/test.js
- appengine/flexible/CloudSql/web.config
Put settings in appsettings.json instead of app.yaml.
Later, I'll change over all the appengine/flexible samples to do the same.
> CloudSql sample for App Engine Flex.

- appengine/flexible/Analytics/Startup.cs
- appengine/flexible/Analytics/app.yaml
- appengine/flexible/Analytics/appsettings.json
- appengine/flexible/Analytics/deployTests.ps1
- appengine/flexible/Analytics/project.json
- appengine/flexible/Analytics/project.lock.json
- appengine/flexible/Analytics/runTests.ps1
- appengine/flexible/RedisCache/app.yaml
- appengine/flexible/RedisCache/appsettings.json
- appengine/flexible/RedisCache/deployTests.ps1
- appengine/flexible/RedisCache/runTests.ps1
- appengine/flexible/SendGrid/app.yaml
- appengine/flexible/SendGrid/appsettings.json
- appengine/flexible/SendGrid/deployTests.ps1
- appengine/flexible/SendGrid/runTests.ps1
It's much easier for users to edit appsettings.json once, than to set an
environment variable, restart Visual Studio, and then edit app.yaml.
> Move environment variables into appsettings.json.

- speech/api/Recognize/Recognize.cs
- speech/api/SpeechTest/SpeechTest.cs
In response to https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/157
> Add a sample and test that demonstrates transcribing a .flac file.

- appengine/flexible/Analytics/README.md
- appengine/flexible/AppEngineFlex.sln
- appengine/flexible/CloudSql/README.md
- appengine/flexible/CloudStorage/README.md
- appengine/flexible/README.md
- appengine/flexible/RedisCache/README.md
- appengine/flexible/SendGrid/README.md
- appengine/flexible/StaticContent/README.md
Add 2 more prerequisites for building and running .NET *core* applications.
> More prerequisites.

- testutil/TestBucket.cs
- testutil/TestUtil.cs
Reviewed by jsimonweb during pair programming.
> Move RandomBucketName() to RandomName().

- compute/sqlserver/powershell/create-availability-group.ps1
- compute/sqlserver/powershell/create-sql-instance-availability-group-cleanup.ps1
- compute/sqlserver/powershell/create-sql-instance-availability-group-prerequisites.ps1
- compute/sqlserver/powershell/create-sql-instance-availability-group.Tests.ps1
- compute/sqlserver/powershell/create-sql-instance-availability-group.ps1
- compute/sqlserver/powershell/parameters-config.ps1
The scripts will automatically create a SQL Server Availability Group
> Scripts to create an Always On Availability Group in Google Cloud

- appengine/flexible/Metadata/Startup.cs
So the doc page can concisely show how to use the metadata server.
> Refactor the metadata sample with doc tags.

- storage/api/Storage/Program.cs
- storage/api/Storage/Storage.csproj
- storage/api/Storage/packages.config
- storage/api/StorageTest/StorageTest.cs
- storage/api/StorageTest/StorageTest.csproj
- storage/api/StorageTest/app.config
Signed urls and encrypted files.
> Add samples for new storage methods.

- endpoints/getting-started/src/IO.Swagger/Dockerfile
- endpoints/getting-started/src/IO.Swagger/app.yaml
- endpoints/getting-started/src/IO.Swagger/deployTests.ps1
To fix https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/205
> Update endpoints sample to use runtime: aspnetcore.

- pubsub/api/PubsubTest.cs
- pubsub/api/PubsubTest.csproj
Fixes https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/118
> Accomodate eventual consistency in Pubsub tests.

- buildAndRunTests.ps1
- kms/api/CloudKmsTest/CloudKmsTest.csproj
- kms/api/QuickStartCore/Program.cs
- kms/api/QuickStartCore/QuickStartCore.xproj
- kms/api/QuickStartCore/project.json
- kms/api/QuickStartCore/runTests.ps1
> Add a KMS sample with dotnet core.

- speech/api/Recognize/Recognize.cs
- speech/api/SpeechTest/SpeechTest.cs
- testutil/TestUtil.cs
Fixes
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/256
> Demonstrate specifying context when recognizing speech.

- endpoints/getting-started/src/IO.Swagger/deployTests.ps1
The instructions for modifying openapi.yaml have changed a little bit.
> Update endpoints' deployTests.ps1

- video/api/Analyze/Program.cs
- video/api/Test/Tests.cs
The faces feature is not ready yet, so replace it.  And only accept local
files for the one feature that accepts uploaded files.
> A sample for Video's safesearch feature.

- spanner/api/Program.cs
- spanner/api/Spanner.csproj
- spanner/api/SpannerTest/SpannerTest.csproj
- spanner/api/packages.config
Because the info messages are not in the docs and may confuse users.
> Write info messages to a logger instead of stdout.

- spanner/api/Program.cs
tags for retry strategy.
removes foreach and uses better parallelization which demonstrates some of the flexibility of the sdk.
> Better parallelization on write.

- pubsub/api/Program.cs
- pubsub/api/Pubsub.csproj
- pubsub/api/PubsubTest/PubsubTest.cs
- pubsub/api/PubsubTest/PubsubTest.csproj
- pubsub/api/PubsubTest/app.config
- pubsub/api/PubsubTest/packages.config
- pubsub/api/QuickStart/App.config
- pubsub/api/QuickStart/QuickStart.csproj
- pubsub/api/QuickStart/packages.config
- pubsub/api/app.config
- pubsub/api/packages.config
Use new api calls to easily maximize pubsub message throughput.
> Simple pubsub

- spanner/api/Program.cs
Minor issue: was missing the end brace.
> include end brace in sample

- appengine/flexible/CloudSql/.gitignore
- appengine/flexible/CloudSql/CloudSql.csproj
- appengine/flexible/CloudSql/Controllers/HomeController.cs
- appengine/flexible/CloudSql/Filters/DbExceptionFilter.cs
- appengine/flexible/CloudSql/README.md
- appengine/flexible/CloudSql/Startup.cs
- appengine/flexible/CloudSql/ViewModels/Home.cs
- appengine/flexible/CloudSql/ViewModels/HomeModel.cs
- appengine/flexible/CloudSql/Views/Home/Index.cshtml
- appengine/flexible/CloudSql/Views/Shared/DbException.cshtml
- appengine/flexible/CloudSql/Views/Shared/Error.cshtml
- appengine/flexible/CloudSql/Views/Shared/_Layout.cshtml
- appengine/flexible/CloudSql/Views/_ViewImports.cshtml
- appengine/flexible/CloudSql/Views/_ViewStart.cshtml
- appengine/flexible/CloudSql/appsettings.json
- appengine/flexible/CloudSql/client.pfx
- appengine/flexible/CloudSql/runTests.ps1
- appengine/flexible/CloudSql/test.js
Factor 4 of 12factor apps:
https://12factor.net/backing-services
Says that you should be able to swap databases without recompiling; just re-deploying.  So build and app that demonstrates it.
> Merge CloudSql MySql sample and PostgreSql sample into one sample.

- compute/sqlserver/powershell/README.md
Created a README.md to help users understand how to use the scripts in this folder.
> Added README.md to provide more information about the files

- .kokoro/main.ps1
- BuildTools.psm1
- datastore/api/TaskListTest/DatastoreTest.csproj
Sort tests by recent git changes, so that the newest test runs first.
> Order tests

- spanner/api/Program.cs
This is just to stress test b/68199801
> Add a "delete sampledata" command

- monitoring/api/MonitoringSample/Program.cs
That's what the doc writer is asking for.
> Actually, don't set the metric name at all.

- video/api/Analyze/Analyze.csproj
- video/api/Analyze/Program.cs
- video/api/QuickStart/Program.cs
- video/api/QuickStart/QuickStart.csproj
- video/api/Test/Test.csproj
Bump package for Video Intelligence to V1
> Update Video Intelligence samples to use V1

- pubsub/api/PubsubTest/PubsubTest.cs
> Retry deletes in pubsub test.

- endpoints/getting-started/src/IO.Swagger/app.yaml
I want to use a docwidget in the docs to display the part of app.yaml that needs to be configured.
> Update comments and add region tags

- README.md
Main README.md didn't clarify that there may be additional customizations required to run specific samples. Fixed that.
> Update instructions on main README.md

- .kokoro-windows/trampoline.ps1
I think it's already installed on the machine.
> Do not install iisexpress.

- .gitignore
- bigquery/api/BigquerySample.sln
- bigquery/api/BigquerySample/Program.cs
- Add additional region tags to support tutorial rewrite.
- Use more relevant query from public datasets.
> BigQuery: rewrite simple app tutorial.

- auth/AuthSample/AuthSample.csproj
- auth/AuthSample/Program.cs
- auth/AuthTest/AuthTest.cs
> Add 3 more samples for gRPC-based APIs.

- appengine/flexible/Analytics/README.md
- appengine/flexible/CloudSql/README.md
- appengine/flexible/CloudStorage/README.md
- appengine/flexible/Datastore/README.md
- appengine/flexible/F#/README.md
- appengine/flexible/HelloWorld/README.md
- appengine/flexible/Metadata/README.md
- appengine/flexible/Pubsub/README.md
- appengine/flexible/README.md
- appengine/flexible/RedisCache/README.md
- appengine/flexible/SendGrid/README.md
- appengine/flexible/SocialAuth/README.md
- appengine/flexible/Stackdriver/README.md
- appengine/flexible/StaticContent/README.md
Change-Id: I83976b21730f9821d7e7da7f91d85aafe8640a9d
> Update appengine READMEs to require VS 2017, because they do.

- pubsub/api/PubsubSample/Program.cs
- pubsub/api/PubsubSample/Pubsub.csproj
- pubsub/api/PubsubTest/PubsubTest.cs
- pubsub/api/PubsubTest/PubsubTest.csproj
- pubsub/api/QuickStart/QuickStart.cs
- pubsub/api/QuickStart/QuickStart.csproj
- testutil/testutil.csproj
This release renames various classes. See http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/ for details.
> Update pubsub sample to use beta16 release

- appengine/flexible/CloudSql/CloudSql.csproj
- appengine/flexible/CloudSql/Program.cs
- appengine/flexible/CloudSql/README.md
- appengine/flexible/CloudSql/Startup.cs
Change-Id: I265af8d9de8c990aacb8bee66a19353099398834
> Update CloudSql sample to .NET core 2.0.

- appengine/flexible/HelloWorld/HelloWorld.csproj
- appengine/flexible/HelloWorld/HelloWorld.sln
- appengine/flexible/HelloWorld/Program.cs
- appengine/flexible/HelloWorld/README.md
- appengine/flexible/HelloWorld/Startup.cs
Change-Id: Ief33d34a9f79cba3e27f31b895c0568fa676b92d
> Update HelloWorld sample from .NET 1.0 to 2.0.

- bigquery/data-transfer/api/BigqueryDataTransferSample.sln
- bigquery/data-transfer/api/QuickStart/Program.cs
- bigquery/data-transfer/api/QuickStart/QuickStart.cs
- bigquery/data-transfer/api/QuickStart/QuickStart.csproj
- bigquery/data-transfer/api/QuickStartTest/QuickStartTest.cs
- bigquery/data-transfer/api/QuickStartTest/QuickStartTest.csproj
- bigquery/data-transfer/api/QuickStartTest/runTests.ps1
This sample lists the data sources enabled for a project.
> Add BigQuery Data Transfer API quickstart

- spanner/api/Spanner/Program.cs
Related:
* ~~googleapis/nodejs-spanner#136~~ merged
* ~~GoogleCloudPlatform/ruby-docs-samples#244~~ merged
* ~~GoogleCloudPlatform/python-docs-samples#1376~~ merged
* ~~GoogleCloudPlatform/java-docs-samples#1045~~ merged
* ~~GoogleCloudPlatform/php-docs-samples#562~~ merged
* ~~GoogleCloudPlatform/golang-samples#403~~ merged
> Clean up Spanner region tags.

- pubsub/api/PubsubTest/PubsubTest.cs
The Eventually() code in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/462 had no effect because the exception thrown is an AggregateException.  So handle AggregateExceptions too.
Change-Id: Ibc93775400b70ca3cb443f83df3341e5ae117c7f
> Fix flaky PubSub test.

- BuildTools.psm1
Sometimes tests fails due to intermittent issues, like a resource being temporarily unavailable.  Maximize the time between test retries to improve the chances that the resource became available.  Do this by retrying failed tests at the end of the test run, instead of retrying them immediately.
Change-Id: I3df38a02a92beaeaaeef6e212c44905192379222
> Retry failed tests at end of test run.

- BuildTools.psm1
- logging/api/LoggingTest/LoggingTest.csproj
- logging/api/LoggingTest/runTests.ps1
Kokoro can consume xunit xml logs and render them in pretty UI.  Try it with one test, to see how it works, before adding it to all our tests.
Change-Id: I4234a87a02d5a094dc6decf3566ce47ca1a4c97c
> Try outputting xunit xml logs during tests.

- .kokoro-windows/common.cfg
- .kokoro/common.cfg
Change-Id: I9ae7bab1eb901e5d4b7fc547eb289ca5e737430a
> Define artifacts for Kokoro build config.

- spanner/api/SpannerTest/runTests.ps1
It can take a while to insert so many rows into the table.
Change-Id: I8ced43da09945079b88f27b6b86f2a6e5fd27c46
> Extend SpannerTest's timeout.

- .kokoro-windows/common.cfg
- .kokoro/common.cfg
- BuildTools.psm1
- logging/api/LoggingTest/LoggingTest.csproj
- logging/api/LoggingTest/runTests.ps1
So rename our logs accordingly.
> Sponge looks for a log file called sponge_log.xml specifically.

- dlp/api/DlpTest/DlpTest.cs
- dlp/api/DlpTest/DlpTest.csproj
- dlp/api/DlpTest/runTest.ps1
But not yet all.
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/510
> Run some DLP tests.

- endpoints/getting-started/openapi.yaml
Update the schemes and echoMessage definition to provide a better user experience in the Developer Portal.
> Updates for Developer Portal

- bigquery/api/BigquerySample/Program.cs
- bigquery/api/BigquerySample/Snippets.cs
- bigquery/api/BigqueryTest/BigqueryTest.cs
- bigquery/api/BigqueryTest/BigqueryTest.csproj
This PR makes the following changes:
- Moves snippets out from BigqueryTest project to BigquerySample project (Snippets.cs).
- Adds bigquery_load_table_gcs_json sample.
- Adds BigqueryTest.TestImportDataFromJSON() test.
- Changes bigquery_load_table_gcs_csv sample.
- Changes BigqueryTest.TestImportFromCloudStorage() test.
> [DO NOT MERGE] Adding load table from JSON; fixing load from CSV example

- storage/api/Storage/Storage.cs
Short PR to fix a typo in sample.
> [Storage] Fix typo in list objects sample

- .kokoro-windows/Initialize-GoogleProjectForTesting.ps1
- texttospeech/api/QuickStart/.gitignore
- texttospeech/api/QuickStart/Program.cs
- texttospeech/api/QuickStart/QuickStart.csproj
- texttospeech/api/README
- texttospeech/api/TextToSpeech.sln
- texttospeech/api/TextToSpeech/TextToSpeech.cs
- texttospeech/api/TextToSpeech/TextToSpeech.csproj
- texttospeech/api/TextToSpeechTest/Tests.cs
- texttospeech/api/TextToSpeechTest/TextToSpeechTest.csproj
- texttospeech/api/TextToSpeechTest/data/hello.ssml
- texttospeech/api/TextToSpeechTest/data/hello.txt
- texttospeech/api/TextToSpeechTest/runTests.ps1
This adds the C# solution for Cloud Text-to-Speech. The solution includes samples the following region tags:
tts_quickstart
tts_list_voices
tts_synthesize_text
tts_synthesize_ssml
tts_synthesize_text_file
tts_synthesize_ssml_file
> Adding C# samples for Text-to-Speech

- logging/api/LoggingSample/Program.cs
Change-Id: I8b612f03de994341cf000639b0c61f4bdc6df821
> Update logging doc tags.

- vision/api/Detect/Program.cs
- vision/api/DetectFaces/DetectFaces.cs
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Vision region tag update

- video/api/Analyze/Program.cs
- video/api/QuickStart/Program.cs
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Video Intelligence region tag update

- BuildTools.psm1
Change-Id: Ic8ca0255c0b5cda83568864fc2caa99a6965425d
> Capture the error message in the log when a powershell script fails.

- appengine/flexible/Analytics/Startup.cs
- appengine/flexible/CloudSql/Controllers/HomeController.cs
- appengine/flexible/CloudSql/Startup.cs
- appengine/flexible/CloudSql/appsettings.json
- appengine/flexible/CloudStorage/Controllers/HomeController.cs
- appengine/flexible/HelloWorld/Startup.cs
- appengine/flexible/Pubsub/Controllers/HomeController.cs
- appengine/flexible/SendGrid/Controllers/HomeController.cs
- appengine/flexible/SendGrid/appsettings.json
- appengine/flexible/Stackdriver/Startup.cs
- appengine/flexible/StaticContent/Startup.cs
- appengine/flexible/StaticContent/wwwroot/index.html
Updating and removing region tags only
> update region tags

- speech/api/Recognize/Recognize.cs
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Speech region tag update

- language/api/Analyze/Program.cs
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Language region tag update

- logging/api/LoggingSample/Program.cs
Change-Id: I8a93b5c0648530fe297d1cfb04c15668248796c9
> Update logging sink doc tags.

- language/api/Analyze/Program.cs
Updates region tags from _file_gcs to _gcs
> NL Region Tag Update

- speech/api/Recognize/Recognize.cs
Updates region tag per feedback
> Update word time offsets region tag

- jobs/api/v2/Jobs.sln
- jobs/api/v2/JobsTest/JobsTest.cs
- jobs/api/v2/JobsTest/JobsTest.csproj
- jobs/api/v2/JobsTest/runTests.ps1
- jobs/api/v2/QuickStart/QuickStart.cs
- jobs/api/v2/QuickStart/QuickStart.csproj
- jobs/api/v2/README.md
Hey Jeff,
Apologies for the confusion. I was told to keep the old v2 sample code from before in a separate folder on the repo so I've gone ahead and added the old version back into the repo. Everything else has stayed the same.
Apologies for the confusion!
> Re-added v2 quick start code

- CONTRIBUTING.md
feel free to find a better set of samples to use as canonical and merge
> add env setup instructions + canonical sample

- translate/canon/DetectLanguage.cs
- translate/canon/ListLanguageCodes.cs
- translate/canon/ListLanguageNames.cs
- translate/canon/README.md
- translate/canon/Test.cs
- translate/canon/Translate.csproj
- translate/canon/TranslateText.cs
- translate/canon/TranslateTextWithModel.cs
- translate/canon/runTests.ps1
example of how samples should be written.
> Refactor translate sample to become the canonical

- pubsub/api/PubsubSample/Program.cs
As seen on https://cloud.google.com/pubsub/docs/pull#synchronous-pull
> Correct sync (non-streaming) pull sample.

- jobs/api/v2/README.md
- jobs/api/v3/JobsSample/Companies.cs
- jobs/api/v3/JobsSample/CustomAttributes.cs
- jobs/api/v3/JobsSample/Jobs.cs
- jobs/api/v3/JobsSample/Search.cs
- jobs/api/v3/QuickStart/QuickStartSearch.cs
- jobs/api/v3/README.md
Hey Jeff,
Very small changes here to fix typos and because job discovery has changed names to Cloud Talent Solution (CTS).
> Fixed code tag typos and adjust name to match rebranding

- pubsub/api/PubsubSample/Program.cs
Also re-factor slightly, and rename simplepub/sub to pub/subclient.
> Add sample for pubsub_subscriber_async_pull

- appengine/flexible/CloudSql/README.md
- jobs/api/v2/README.md
- jobs/api/v3/JobsSample/README.md
- jobs/api/v3/QuickStart/README.md
- kms/api/CloudKmsAspNetSample/README.md
- kms/api/CloudKmsSample/README.md
- kms/api/QuickStart/README.md
Change-Id: Idfb1fb15e782c88a5c58665fc8612c0b11f4db52
> Replace pantheon.corp.google.com with console.cloud.google.com.

- CONTRIBUTING.md
Change-Id: I6e73872228a82d447c2c49e27c7aaef84bc8e870
> Call out translate as the canonical sample.

- pubsub/api/PubsubSample/Program.cs
Explaining returned Task from PublishAsync a little
Fixes https://github.com/googleapis/google-cloud-dotnet/issues/2532
> Add comment to pubsub publish sample

- appengine/flexible/Stackdriver/Startup.cs
Corresponding doc is https://cloud.google.com/trace/docs/setup/aspnetcore.
> Rename region tags in aspnetcore sample.

- trace/api/Controllers/TraceController.cs
- trace/api/Global.asax.cs
- trace/api/Web.config
Change-Id: Ie9de0a2258dc5a83df533dca6ee66602bae77ce1
> Remove old region tags.

- appengine/flexible/Stackdriver/Controllers/ForceErrorController.cs
- appengine/flexible/Stackdriver/Startup.cs
Change-Id: I3ee18b3f682da92caaea6630a3870f04374ed4a4
> Rename error reporting region tags.

- firestore/api/AddData/Program.cs
- firestore/api/DataModel/DataModel.csproj
- firestore/api/DeleteData/DeleteData.csproj
- firestore/api/DeleteData/Program.cs
- firestore/api/FirestoreTest/FirestoreTest.cs
- firestore/api/FirestoreTest/FirestoreTest.csproj
- firestore/api/GetData/GetData.csproj
- firestore/api/GetData/Program.cs
- firestore/api/ListenData/ListenData.csproj
- firestore/api/ListenData/Program.cs
- firestore/api/ManageIndexes/ManageIndexes.csproj
- firestore/api/ManageIndexes/Program.cs
- firestore/api/OrderLimitData/OrderLimitData.csproj
- firestore/api/OrderLimitData/Program.cs
- firestore/api/PaginateData/PaginateData.csproj
- firestore/api/PaginateData/Program.cs
- firestore/api/QueryData/Program.cs
- firestore/api/QueryData/QueryData.csproj
- firestore/api/Quickstart/Program.cs
- firestore/api/Quickstart/Quickstart.csproj
- firestore/api/README.md
- firestore/api/TransactionsAndBatchedWrites/Program.cs
- firestore/api/TransactionsAndBatchedWrites/TransactionsAndBatchedWrites.csproj
- New samples: Watch, Document Snapshot Cursors, Array Queries
- Library update from 1.0.0-beta02 to 1.0.0-beta11
- Added DoesNotContain checks to all tests
- Removed writeResult.UpdateTime print outs because they aren't necessary
- Updated README instructions for Cloud Console rather than Firebase Console
> New Firestore Samples + Library Improvements + Testing Improvements

- bigtable/api/BigtableTest/runTests.ps1
Change-Id: I3f3fba9dba45b326bbd9bdfebf00a2fd57798dc3
> Skip the bigtable test until it's fixed.

- bigtable/api/InstanceAdminExample/InstanceAdmin.cs
- bigtable/api/InstanceAdminExample/InstanceAdmin.csproj
- bigtable/api/QuickStart/QuickStart.cs
- bigtable/api/QuickStart/QuickStart.csproj
- bigtable/api/TableAdminExample/TableAdmin.cs
- bigtable/api/TableAdminExample/TableAdmin.csproj
Updated dependencies and appropriate code adjustments for
* QuickStart
* InstanceAdmin
* TableAdmin
> Bigtable: update examples dependencies

- bigtable/api/HelloWorld/HelloWorld.cs
- bigtable/api/HelloWorld/HelloWorld.csproj
* Updated dependencies
* Updated implementation of `TableExist` method
* Added region tags
> Bigtable: update Hello World

- bigtable/api/BigtableTest/runTests.ps1
Change-Id: I6d0d58f680cc53357dc0f70f2457cc222bb893ef
> Skip bigtable test until it can be fixed.

- bigtable/api/HelloWorld/HelloWorld.cs
Added `creating_a_filter` region tag to follow the standard across examples in other languages.
> Bigtable: add filter region tag to hello world sample

- vision/api/VisionTest/runTests.ps1
Change-Id: I449f7eb9420d52a6c68e5730eb63df3bfbb44e67
> Extend Vision Test timeout, because it has been timing out lately.

- spanner/api/Spanner/Program.cs
I want to include this example in the docs.
> Add snippet tags to code sample that deletes data.

- spanner/api/Spanner/Program.cs
It fixes some rendering issues in the docs.
> Fixed tabs/spaces so that they are consistent.

- appengine/flexible/Analytics/README.md
- appengine/flexible/CloudSql/README.md
- appengine/flexible/CloudStorage/README.md
- appengine/flexible/Datastore/README.md
- appengine/flexible/F#/README.md
- appengine/flexible/HelloWorld/README.md
- appengine/flexible/Metadata/README.md
- appengine/flexible/Pubsub/README.md
- appengine/flexible/README.md
- appengine/flexible/RedisCache/README.md
- appengine/flexible/SendGrid/README.md
- appengine/flexible/SocialAuth/README.md
- appengine/flexible/Stackdriver/README.md
- appengine/flexible/StaticContent/README.md
Change-Id: I595c94797e1f39ebc2bdeb2b0499b849b4343994
> Update link and text to download .NET SDK.

- applications/leaderboard/Leaderboard/Leaderboard.csproj
- spanner/api/Spanner/Spanner.csproj
> Update dependency on command line library.

- spanner/api/Spanner.sln
Fixes https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/723
> Fix Spanner.sln so it builds with Visual Studio.

- kms/api/CloudKmsSample/CloudKmsSample.csproj
- kms/api/CloudKmsSample/Program.cs
- kms/api/CloudKmsTest/CloudKmsTest.cs
- kms/api/CloudKmsTest/CloudKmsTest.csproj
- kms/api/QuickStart/QuickStart.cs
- kms/api/QuickStart/QuickStart.csproj
> Convert Cloud KMS samples to GAPIC clients

- vision/api/VisionTest/VisionTest.cs
Change-Id: I915b2d260d2e551ad9d974739feccf6151757074
> Vision no longer sees a 'mammal.' It sees a cat.

- datastore/api/TaskListTest/DatastoreTest.cs
* `datastore_transactional_single_entity_group_read_only`
> docs(samples): Update Datastore snippet for read only transaction

- texttospeech/api/QuickStart/QuickStart.csproj
- texttospeech/api/TextToSpeech/TextToSpeech.cs
- texttospeech/api/TextToSpeech/TextToSpeech.csproj
- texttospeech/api/TextToSpeechTest/Tests.cs
This code sample adds the following region tags:
* tts_synthesize_text_audio_profile
The Python canonical sample is here:
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/texttospeech/cloud-client/audio_profile.py
> Text-to-Speech device audio profiles samples

- irm/api/Snippets/ChangeSeverity.cs
Should have been part of https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/743
> Accomodate more review comments.

- irm/api/Snippets/ChangeStage.cs
- irm/api/Snippets/CreateIncident.cs
The server implementation has been updated so the hack is no longer necessary.
Change-Id: I48bf1b10a150038cfb905591a88d1aadb827e106
> Remove the name hack.

- video/api/Analyze/Analyze.csproj
- video/api/Analyze/Program.cs
- video/api/Test/Test.csproj
- video/api/Test/Tests.cs
This pull request adds the following code snippets / region tags:
* video_object_tracking_gcs
* video_object_tracking
* video_detect_text
* video_detect_text_gcs
Python canonicals are here:
* [Text detection](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/video/cloud-client/analyze/beta_snippets.py#L83-L172)
* [Object tracking](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/video/cloud-client/analyze/beta_snippets.py#L176-L273)
> Video Intelligence text detection, object tracking

- video/api/Test/runTests.ps1
Change-Id: I739a80aef9f0870aff82f77e83833d8cc5885da2
> Increase the video timeout some more, because it still times out.

- video/api/Test/Tests.cs
Change-Id: I323c832fb160b042070e0d2ff219d7ceb2c547d2
> Print a detailed error message when text detection test fails.

- iot/api/CloudIotMqttExample/Program.cs
Added a filter that will fix invalidcast exception which was caused by unsupported private keys,
> added a check that allows only certain private key

- kms/api/CloudKmsAspNetSample/Services/EncryptedFileProvider.cs
As documented in
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/753
Change-Id: I4253dc8ac99623708e176dd064046affcb9985c1
> Fix infinite recursion.

- appengine/flexible/Datastore/Datastore.csproj
Had to clean up .csproj a bit to make it work.
Change-Id: I5d3600fdbacadf50e96aa8eae9af28a79cdca4f7
> Upgrade datastore appengine app to use 2.2 library.

- appengine/flexible/Pubsub/Controllers/HomeController.cs
- appengine/flexible/Pubsub/Pubsub.csproj
- appengine/flexible/Pubsub/Startup.cs
Change-Id: I98ae9d034527d3f632633d388ab25c8d5fcf449e
> Update Pubsub Appengine application to use new API.

- bigtable/api/HelloWorld/HelloWorld.cs
- bigtable/api/InstanceAdminExample/InstanceAdmin.cs
- bigtable/api/QuickStart/QuickStart.cs
- bigtable/api/README.md
> Typo fixes in C# samples

- iot/api/CloudIotMqttExample/Program.cs
> Consistent prefix for product name

- storage/api/Storage/Storage.cs
- storage/api/Storage/Storage.csproj
> Add V4 signing samples

- logging/api/LoggingTest/LoggingTest.cs
When an attempt to delete a log or a sink throws an exception, continue trying to delete the rest.
Change-Id: I08c864c14e3a6ea9a0e6c09c19522583b8bcbb26
> Fix LoggingTest clean up code.

- speech/api/Recognize/Recognize.cs
- speech/api/Recognize/Recognize.csproj
Fixes https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/425
> Upgrade NAudio to 1.9.

- vision/api/Detect/Detect.csproj
- vision/api/ProductSearch/ProductSearch.csproj
It causes problems like https://github.com/googleapis/google-cloud-dotnet/issues/3240.
Change-Id: Ia744cb9b644707447a6b2ecafad1d77f2bde8e21
> Remove unnecessary dependency on Google.Protobuf.

- storage/api/Storage/Storage.cs
cc: @JesseLovelace 
Track sample by adding region tag.
> [Storage] Add LocationType to GetBucketMetadata sample

- .kokoro-windows/New-BuildEnv.ps1
Change-Id: Ib8b3e009c5459506fba2d56211411d210ac226d4
> Upgrade selenium-chrome-driver to 76 to fix failing test.

- CONTRIBUTING.md
Linking to the canonical test sample
> Updating contributing doc

- vision/api/ProductSearch/ProductInProductSetManagement.cs
- vision/api/ProductSearch/ProductManagement.cs
- vision/api/ProductSearch/ProductSearch.csproj
- vision/api/VisionTest/ProductSearchTest.cs
samples for new features:
- delete all products in a product set
- delete all products not in any product sets
> Purge products 

- iam/api/ServiceAccountTests/ServiceAccountTests.cs
- iam/api/ServiceAccounts/Main.cs
- iam/api/ServiceAccounts/Options.cs
- iam/api/ServiceAccounts/ServiceAccountsDisable.cs
- iam/api/ServiceAccounts/ServiceAccountsEnable.cs
Adding service account enable/disable snippets to go along with this doc addition: https://critique.corp.google.com/#review/267282634
> Add service account enable/disable snippets

- CODEOWNERS
So pull requests are automatically assigned.
> Add Amanda to CODEOWNERS.

- appengine/flexible/Stackdriver/Startup.cs
- applications/sudokumb/WebApp/Startup.cs
- applications/sudokumb/WebSolver/Startup.cs
- applications/sudokumb/runTests.ps1
- bigtable/api/Bigtable.sln
- bigtable/api/InstanceAdminExample/InstanceAdmin.cs
- bigtable/api/SnippetsTest/SnippetsTest.csproj
- logging/api/AspNetCore/Startup.cs
We recently released almost all .NET client libraries, some with known breaking changes.
This PR fixes such breaking changes.
> Fixes dependecy updates breakages.

- .kokoro-windows/Initialize-GoogleProjectForTesting.ps1
- secretmanager/api/QuickStart/QuickStart.cs
- secretmanager/api/QuickStart/QuickStart.csproj
- secretmanager/api/QuickStart/README.md
- secretmanager/api/SecretManagerSample/Program.cs
- secretmanager/api/SecretManagerSample/README.md
- secretmanager/api/SecretManagerSample/SecretManagerSample.csproj
- secretmanager/api/SecretManagerTest/QuickStartTests.cs
- secretmanager/api/SecretManagerTest/SamplesTest.cs
- secretmanager/api/SecretManagerTest/SecretManagerTest.cs
- secretmanager/api/SecretManagerTest/SecretManagerTest.csproj
- secretmanager/api/SecretManagerTest/SecretsFixture.cs
- secretmanager/api/SecretManagerTest/runTests.ps1
I also noticed there's some fun Koroko scripts that download secrets from GCS. Let me know if you'd like some help to migrate those to Secret Manager 😉
> secretmanager: add initial samples

- vision/api/VisionTest/ProductSearchTest.cs
Addresses a potential issue with simultaneous tests by randomizing product IDs for Product Search tests.
> Adds randomization to test product ID names

- storage/api/README.md
- storage/api/Storage/Storage.cs
- storage/api/Storage/Storage.csproj
- storage/api/StorageTest/StorageTest.cs
> [Storage] feat(#955): add support for Iam conditions

- secretmanager/api/QuickStart/QuickStart.cs
- secretmanager/api/QuickStart/QuickStart.csproj
- secretmanager/api/SecretManagerSample/Program.cs
- secretmanager/api/SecretManagerSample/SecretManagerSample.csproj
- secretmanager/api/SecretManagerTest/QuickStartTests.cs
- secretmanager/api/SecretManagerTest/SamplesTest.cs
- secretmanager/api/SecretManagerTest/SecretsFixture.cs
Client library has been published: https://www.nuget.org/packages/Google.Cloud.SecretManager.V1
> [Secret Manager] Updated version v1beta1->v1

- speech/api/Recognize/Recognize.cs
Also adds comment about using a local file.
This changes the following region tags:
speech_transcribe_multichannel_beta => speech_transcribe_multichannel
> fix: removes '_beta' from multichan sample

- storage/api/Storage.sln
- storage/api/Storage/CreateBucket.cs
- storage/api/Storage/CreateNewBucket.cs
- storage/api/Storage/CreateRegionalBucket.cs
- storage/api/Storage/Storage.cs
> refactor(storage): separate sample for create bucket

- video/api/Analyze/Program.cs
- video/api/Test/Test.csproj
- video/api/Test/Tests.cs
- video/api/Video.sln
canonical sample: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3098
> video:logo detect GA[URGENT]

- pubsub/api/PubsubSample/Program.cs
* Adds some error handling to the sample which will benifit other sampes as well.
Fixes #861
> PubSub: Makes pubsub_publish tag actually show some publishing sample code.

- spanner/api/SpannerTest/Tests.cs
> Spanner: separate tests for datatypes 

- CODEOWNERS
FYI @sethvargo @skuruppu @jsimonweb .
> Updates CODEOWNERS

- CODEOWNERS
* Sets idiomacy reviewers on all samples.
* Sets owners of some new samples.
@jskeet I've added you mostly for when I'm not available, you can ignore review requests for sample PRs otherwise.
> Updates CODEOWNERS.

- .kokoro-windows/trampoline.ps1
- .kokoro/main.ps1
- language/api/AnalyzeTest/runTests.ps1
- spanner/api/SpannerTest/Tests.cs
- storage/api/StorageTest/StorageTest.cs
> Deactivates some flaky tests.

- functions/helloworld/HelloGcs/Function.cs
- functions/helloworld/HelloGcs/HelloGcs.csproj
- functions/helloworld/HelloHttp/Function.cs
- functions/helloworld/HelloHttp/HelloHttp.csproj
- functions/helloworld/HelloWorld.Tests/FunctionTestBase.cs
- functions/helloworld/HelloWorld.Tests/HelloGcsTest.cs
- functions/helloworld/HelloWorld.Tests/HelloHttpTest.cs
- functions/helloworld/HelloWorld.Tests/HelloWorld.Tests.csproj
- functions/helloworld/HelloWorld.sln
- functions/helloworld/runTests.ps1
- functions/update-functions-framework.sh
(Not urgent - I'm not expecting this to be reviewed before Monday!)
I thought it would be worth creating just a couple of samples to start with to get feedback, before rolling out the remaining 30+ samples.
Note that this is deliberately using the version of the Functions Framework that doesn't use Google.Events yet - when we publish 1.0.0-alpha08 of the Functions Framework, we'll need to change some code here; that will be a good process test.
> First Functions samples

- functions/helloworld/HelloGcsGeneric/Function.cs
- functions/helloworld/HelloGcsGeneric/HelloGcsGeneric.csproj
- functions/helloworld/HelloWorld.Tests/HelloGcsGenericTest.cs
- functions/helloworld/HelloWorld.Tests/HelloWorld.Tests.csproj
- functions/helloworld/HelloWorld.sln
Corresponding Java sample: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/functions/helloworld/hello-gcs-generic/src/main/java/functions/HelloGcsGeneric.java
> Add HelloGcsGeneric sample

- storage/api/StorageTest/StorageTest.cs
> test: fix storage service account

- pubsub/api/Pubsub.Samples.Tests/PubsubFixture.cs
- pubsub/api/Pubsub.Samples.Tests/PullMessagesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullMessagesWithFlowControlAsyncTest.cs
- pubsub/api/Pubsub.Samples/PullMessagesAsync.cs
- pubsub/api/Pubsub.Samples/PullMessagesWithFlowControlAsync.cs
The first commit will take care of some warnings we are getting.
The second commit should take care of some flakinnes seen on #1117
> Pub/Sub minor fixes.

- functions/imagemagick/ImageMagick.sln
- functions/imagemagick/ImageMagick/Function.cs
- functions/imagemagick/ImageMagick/ImageMagick.csproj
- functions/imagemagick/README.md
- functions/imagemagick/runTests.ps1
See https://cloud.google.com/functions/docs/tutorials/imagemagick
for examples in other languages.
Currently there's no automated test for this - see README.md for
details.
> Add Functions sample for ImageMagick

- appengine/flexible/RedisCache/Controllers/HomeController.cs
- appengine/flexible/RedisCache/Startup.cs
- bigtable/api/Snippets/Filters.cs
- bigtable/api/Snippets/Reads.cs
- iot/api/CloudIotSample/Program.cs
- texttospeech/api/TextToSpeech/TextToSpeech.cs
And fixes mismatched tags found by it.
See snippet-bot's [README](https://github.com/googleapis/repo-automation-bots/blob/master/packages/snippet-bot/README.md).
> Activates the snippet-bot.

- functions/concepts/Concepts.Tests/Concepts.Tests.csproj
- functions/concepts/Concepts.Tests/LazyFieldsTest.cs
- functions/concepts/Concepts.sln
- functions/concepts/LazyFields/Function.cs
- functions/concepts/LazyFields/LazyFields.csproj
- functions/helloworld/HelloWorld.Tests/HelloPubSubUnitTest.cs
- functions/slack/README.md
- functions/slack/Slack.sln
- functions/slack/SlackKnowledgeGraphSearch/Function.cs
- functions/slack/SlackKnowledgeGraphSearch/SlackKnowledgeGraphSearch.csproj
- functions/slack/SlackKnowledgeGraphSearch/SlackRequestVerifier.cs
- functions/slack/SlackKnowledgeGraphSearch/Startup.cs
- functions/slack/runTests.ps1
These are the final samples for Functions as far as I'm aware.
The Slack sample has been tested in Slack itself (discovering a number of issues that wouldn't have shown up in tests). It fails with timeouts more often than I'd like, but that's not really fixable within the framework of what we're doing.
> More functions samples

- pubsub/api/Pubsub.Samples/CreateSubscriptionWithOrdering.cs
- pubsub/api/Pubsub.Samples/PublishOrderedMessagesAsync.cs
- pubsub/api/Pubsub.Samples/ResumePublish.cs
A previous PR #1148 did not use the right region tags for the samples. 
Cc: @kamalaboulhosn
> Pub/Sub: update region tags

- pubsub/api/Pubsub.Samples.Tests/DetachSubscriptionTest.cs
- pubsub/api/Pubsub.Samples/DetachSubscription.cs
- pubsub/api/Pubsub.Samples/Pubsub.Samples.csproj
> [Pub/Sub]: Detach Subscription Sample 

- functions/helloworld/HelloWorld/HelloWorld.csproj
- functions/helloworld/HelloWorldFSharp/HelloWorldFSharp.fsproj
- functions/helloworld/HelloWorldVb/HelloWorldVb.vbproj
> Add tags to Functions "hello world" project files

- pubsub/api/Pubsub.Samples/PublishOrderedMessagesAsync.cs
Here is the issue in NodeJS: https://github.com/googleapis/nodejs-pubsub/issues/1136
> Pub/Sub: regional endpoint in publish ordered message

- cloud-sql/mysql/Startup.cs
- cloud-sql/postgres/Startup.cs
- cloud-sql/sql-server/Startup.cs
Replaced singleton dbConnection creator with scoped creator
Fixes #1199
> Changed DB connection init to not use Singletons

- speech/api/Recognize/Recognize.cs
- speech/api/SpeechTest/SpeechTest.cs
I am adding a simple sample that showcases the use of the profanity filter feature.
> feat: [Speech] Adds a profanity filter sample

- speech/api/QuickStart/QuickStart.cs
- speech/api/SpeechTest/SpeechTest.cs
No longer uses a local resource file
> refactor: quickstart now uses gcs

- speech/api/QuickStart/QuickStart.cs
- speech/api/Recognize/Recognize.cs
- speech/api/SpeechTest/SpeechTest.cs
This new sample shows how to change the default multi-region endpoint
> feat: adds a new multi region sample

- storage/api/Storage.Samples/EnableBucketLifecycleManagement.cs
- storage/api/Storage.Samples/Storage.Samples.csproj
This updates the sample to account for a breaking change in the
apiary client. This PR also bumps the apiary library to the latest
released version.
> fix(storage): update CustomTime and NonCurrentTime

- spanner/api/Spanner.Samples/CreateDatabaseAsync.cs
Batch DDL statements to reduce execution time and reduce the number of DDL requests to Spanner.
Fixes #1251
> feat(Spanner): batch DDL statements in CreateDatabase sample

- dialogflow/api/DialogflowSamples/DialogflowSamples.csproj
- dialogflow/api/Test/DetectIntentStreamTest.cs
- dialogflow/api/Test/DialogflowSampleTests.csproj
> chore: re-enable disabled test since quotas already increased

- endpoints/getting-started/NuGet.Config
See [Microsoft's white paper](https://aka.ms/pkg-sec-wp) for more information about dependency confusion attack. Recreation of https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1269/
> Don't mix private and public feeds

- .kokoro/docker/Dockerfile
Please use mcr.microsoft.com for the best support.  https://azure.microsoft.com/en-us/blog/microsoft-syndicates-container-catalog/
> Fix PowerShell from statement to be from current location

- .github/blunderbuss.yml
- CODEOWNERS
Updates the CODEOWNERs file and Blunderbuss config for new teamsync managed groups
Before merging, please make sure the follow teams have write access for this repo:
> Update CODEOWNERS / Blunderbuss for SoDA teams 

- compute/api/Compute.Samples.Tests/ComputeFixture.cs
- compute/api/Compute.Samples.Tests/CreateInstanceAsyncTest.cs
- compute/api/Compute.Samples/CreateInstanceAsync.cs
- compute/api/Compute.Samples/DeleteInstanceAsync.cs
- compute/api/Compute.Samples/DisableUsageExportBucketAsync.cs
- compute/api/Compute.Samples/SetUsageExportBucketAsync.cs
> docs(Compute): Change wording of polling comments

- cloud-sql/sql-server/Startup.cs
> Add SQL Server sample connection string setting

- spanner/api/Spanner.Samples/CreateConnectionWithQueryOptionsAsync.cs
- spanner/api/Spanner.Samples/RunCommandWithQueryOptionsAsync.cs
> samples(spanner): fix optimizer stats pkg sample

- spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
> spanner: cleanup stale instances before starting new test cycle

- .github/renovate.json
In the end I didn't include the two failing updates on the ignore path.
I want to see how best to work with the PRs that this will generate. Maybe the fixes are easy even.
> chore: Activate renovate

- spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
We are reaching quota sometimes.
> tests(spanner): Delete more stale databases and backups.

- cloud-sql/mysql/Program.cs
- cloud-sql/postgres/Program.cs
- cloud-sql/sql-server/Program.cs
> Intialize DB before app run in Cloud SQL samples

- .github/renovate.json
> chore: Disable renovate dashboard.

- appengine/flexible/Pubsub/README.md
- applications/googlehome-meets-dotnetcontainers/Readme.md
- bigtable/api/README.md
- iot/api/README.md
- spanner/api/README.md
Updating README.md for PubSub, Bigtable, IOT, and Spanner
> Updating README.md for PubSub, Bigtable, IOT, and Spanner

- storage/api/Storage.Samples.Tests/SetPublicAccessPreventionInheritedTest.cs
- storage/api/Storage.Samples/SetPublicAccessPreventionInherited.cs
> feat(Storage): Adds sample for PAP inherited.

- iot/api/CloudIotTest/CloudIotTest.cs
- pubsub/api/Pubsub.Samples.Tests/EmulatorSupportTest.cs
- pubsub/api/Pubsub.Samples.Tests/PublishAvroMessagesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PublishBatchMessageTest.cs
- pubsub/api/Pubsub.Samples.Tests/PublishMessageTest.cs
- pubsub/api/Pubsub.Samples.Tests/PublishMessageWithCustomAttributesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PublishMessageWithRetrySettingsAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PublishOrderedMessagesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PublishProtoMessagesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullAvroMessagesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullMessageWithLeaseManagementTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullMessagesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullMessagesAsyncWithDeliveryAttemptsTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullMessagesWithCustomAttributesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullMessagesWithFlowControlAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullProtoMessagesAsyncTest.cs
- pubsub/api/Pubsub.Samples.Tests/ResumePublishTest.cs
- pubsub/api/Pubsub.Samples/EmulatorSupport.cs
And fixes some `async void` in a separate commit.
> feat(PubSub): Adds emulator support sample

- storagetransfer/api/StorageTransfer.Samples.Tests/QuickstartTest.cs
- storagetransfer/api/StorageTransfer.Samples.Tests/StorageFixture.cs
- storagetransfer/api/StorageTransfer.Samples.Tests/StorageTransfer.Samples.Tests.csproj
- storagetransfer/api/StorageTransfer.Samples/QuickstartSample.cs
- storagetransfer/api/StorageTransfer.Samples/StorageTransfer.Samples.csproj
- storagetransfer/api/StorageTransfer.sln
- storagetransfer/api/runTests.ps1
Adds the storagetransfer directory, a quickstart for transfer service, and a test
> Add transfer service quickstart

- run/helloworld/Dockerfile
- run/helloworld/Program.cs
- run/helloworld/helloworld.csproj
> Add a Cloud Run hello world sample using .NET 6.0 #1596

- bigquery-storage/api/BigQueryStorage.Samples.Tests/AppendRowsPendingTests.cs
Code clean-up as suggested by Amanda
> fix(BigQuery.Storage): Code clean-up

- retail/interactive-tutorial/RetailSearch.Samples.Tests/SearchWithNextPageTokenTest.cs
- retail/interactive-tutorial/RetailSearch.Samples.Tests/SearchWithOffsetTest.cs
- retail/interactive-tutorial/RetailSearch.Samples.Tests/SearchWithPageSizeTest.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchSimpleQuerySample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithBoostSpecSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithFacetSpecSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithFilteringSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithNextPageTokenSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithOffsetSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithOrderingSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithPageSizeSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithQueryExpansionSample.cs
Divided pagination sample into 3 different samples:
**1. SearchWithPageSizeSample
2. SearchWithOffsetSample
3. SearchWithNextPageTokenSample**
> Divided pagination sample into 3 different samples

- functions/helloworld/HelloGcs/Function.cs
> chore(functions/helloGcs): add explanatory comment

- cloud-sql/postgres/ConnectTcp.cs
- cloud-sql/postgres/ConnectUnix.cs
- cloud-sql/postgres/Controllers/HomeController.cs
- cloud-sql/postgres/README.md
- cloud-sql/postgres/Startup.cs
- cloud-sql/postgres/app.yaml
- cloud-sql/postgres/runTestsWithPostgreSql.ps1
- Move TCP and UNIX socket examples into separate files
- Update region tags
- Update DB_HOST env. variable to be INSTANCE_HOST
- Update DB_SOCKET_PATH env. variable to be INSTANCE_UNIX_SOCKET
> feat(cloud-sql/postgres): update to V2 sample

- cloud-sql/sql-server/ConnectTcp.cs
- cloud-sql/sql-server/Controllers/HomeController.cs
- cloud-sql/sql-server/README.md
- cloud-sql/sql-server/Startup.cs
- cloud-sql/sql-server/app.yaml
- cloud-sql/sql-server/runTestsWithSqlServer.ps1
- Move TCP socket example into separate file
- Update region tags
- Update DB_HOST env. variable to be INSTANCE_HOST
> feat(cloud-sql/sql-server): update to V2 sample

- cloud-sql/mysql/ConnectTcp.cs
- cloud-sql/mysql/ConnectUnix.cs
- cloud-sql/mysql/Controllers/HomeController.cs
- cloud-sql/mysql/README.md
- cloud-sql/mysql/Startup.cs
- cloud-sql/mysql/app.yaml
- cloud-sql/mysql/runTestsWithMySql.ps1
- Move TCP and UNIX socket examples into separate files
- Update region tags
- Update DB_HOST env. variable to be INSTANCE_HOST
- Update DB_SOCKET_PATH env. variable to be INSTANCE_UNIX_SOCKET
> feat(cloud-sql/mysql): update to V2 sample

- cloud-sql/sql-server/runTestsWithSqlServer.ps1
> Enable SQL Server integration tests.

- appengine/flexible/Pubsub/Controllers/HomeController.cs
- appengine/flexible/Pubsub/Pubsub.csproj
- appengine/flexible/Pubsub/PubsubOptions.cs
- appengine/flexible/Pubsub/Startup.cs
- appengine/flexible/Pubsub/ViewModels/MessageList.cs
- appengine/flexible/Pubsub/Views/Home/Index.cshtml
- appengine/flexible/Pubsub/appsettings.json
- appengine/flexible/Pubsub/deployTest.js
Added pub-sub auth push [sample]([url](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/1234))
Please review
> Pub-Sub Auth Push sample

- datastore/admin-api/DatastoreAdmin.Samples.Tests/DatastoreAdmin.Samples.Tests.csproj
- datastore/admin-api/DatastoreAdmin.Samples/DatastoreAdmin.Samples.csproj
- datastore/api/QuickStart/QuickStart.csproj
- datastore/api/QuickStartTest/QuickStartTest.csproj
- datastore/api/TaskList/TaskList.csproj
- datastore/api/TaskListTest/DatastoreTest.csproj
Manually, as some dependencies need to be updated together.
> build(Datastore): Update dependencines to GAX V4.

- iot/api/CloudIotMqttExampleTest/CloudIotMqttTest.cs
- iot/api/CloudIotMqttExampleTest/CloudIotMqttTest.csproj
- iot/api/CloudIotTest/CloudIotTest.cs
- iot/api/CloudIotTest/CloudIotTest.csproj
- pubsub/api/Pubsub.Samples.Tests/Pubsub.Samples.Tests.csproj
- pubsub/api/Pubsub.Samples/GetSubscriptionIamPolicy.cs
- pubsub/api/Pubsub.Samples/GetTopicIamPolicy.cs
- pubsub/api/Pubsub.Samples/Pubsub.Samples.csproj
- pubsub/api/Pubsub.Samples/SetSubscriptionIamPolicy.cs
- pubsub/api/Pubsub.Samples/SetTopicIamPolicy.cs
- pubsub/api/Pubsub.Samples/TestSubscriptionIamPermissions.cs
- pubsub/api/Pubsub.Samples/TestTopicIamPermissions.cs
- storage/api/Storage.Samples.Tests/Storage.Samples.Tests.csproj
- storage/api/Storage.Samples.Tests/StorageFixture.cs
Mostly because of Pub/Sub having been released as GA.
> deps: Update some dependencies to GAX V4

- retail/interactive-tutorial/RetailProducts.Samples/UpdateProductSample.cs
- Fixed console output in UpdateProductSample.
- Added using directive.
> Fixed console output

- retail/interactive-tutorial/RetailProducts.Samples.Tests/AddFulfillmentPlacesTest.cs
- retail/interactive-tutorial/RetailProducts.Samples.Tests/RemoveFulfillmentInfoTest.cs
- retail/interactive-tutorial/RetailProducts.Samples.Tests/SetInventoryTest.cs
- retail/interactive-tutorial/RetailProducts.Samples/AddFulfillmentPlacesSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/RemoveFulfillmentPlacesSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/SetInventorySample.cs
Added long-running samples:
- AddFulfillment + test
- RemoveFulfillment + test
- SetInventory + test
> Added long-running samples and tests(copy)

- retail/interactive-tutorial/user_environment_setup.sh
- retail/interactive-tutorial/user_import_data_to_catalog.sh
- added `user_environment_setup.sh`
- added `user_import_data_to_catalog.sh`
> Environment setup and import data scripts

- retail/interactive-tutorial/RetailEvents.Samples/setup/EventsCreateBigQueryTable.cs
- retail/interactive-tutorial/RetailProducts.Samples/setup/ProductsCreateBigQueryTable.cs
- retail/interactive-tutorial/TestResourcesSetupCleanup/CreateTestResources.cs
- created invalid events BQ table.
- created invalid products BQ table.
> Invalid test resources creation

- media/livestream/api/LiveStream.Samples.Tests/CreateChannelEventTests.cs
- media/livestream/api/LiveStream.Samples.Tests/DeleteChannelEventTests.cs
- media/livestream/api/LiveStream.Samples.Tests/GetChannelEventTests.cs
- media/livestream/api/LiveStream.Samples.Tests/ListChannelEventsTests.cs
- media/livestream/api/LiveStream.Samples.Tests/LiveStreamFixture.cs
- media/livestream/api/LiveStream.Samples/CreateChannelEvent.cs
- media/livestream/api/LiveStream.Samples/DeleteChannelEvent.cs
- media/livestream/api/LiveStream.Samples/GetChannelEvent.cs
- media/livestream/api/LiveStream.Samples/ListChannelEvents.cs
b:241866780
Part 3 of 3: Channel events. See also https://cloud.google.com/livestream/docs/how-to/create-channel-events
> feat(Livestream): Add samples and tests

- retail/interactive-tutorial/RetailProducts.Samples/AddFulfillmentPlacesSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/RemoveFulfillmentPlacesSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/SetInventorySample.cs
We have failures during tests. So, removed timeStamp may help us avoid this issue.
> LRO without timestamps

- media/stitcher/api/Stitcher.Samples.Tests/CreateCdnKeyTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/CreateSlateTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/DeleteCdnKeyTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/DeleteSlateTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/GetCdnKeyTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/GetSlateTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/ListCdnKeysTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/ListSlatesTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/Stitcher.Samples.Tests.csproj
- media/stitcher/api/Stitcher.Samples.Tests/StitcherFixture.cs
- media/stitcher/api/Stitcher.Samples.Tests/UpdateCdnKeyTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/UpdateSlateTests.cs
- media/stitcher/api/Stitcher.Samples/CreateCdnKey.cs
- media/stitcher/api/Stitcher.Samples/CreateSlate.cs
- media/stitcher/api/Stitcher.Samples/DeleteCdnKey.cs
- media/stitcher/api/Stitcher.Samples/DeleteSlate.cs
- media/stitcher/api/Stitcher.Samples/GetCdnKey.cs
- media/stitcher/api/Stitcher.Samples/GetSlate.cs
- media/stitcher/api/Stitcher.Samples/ListCdnKeys.cs
- media/stitcher/api/Stitcher.Samples/ListSlates.cs
- media/stitcher/api/Stitcher.Samples/Stitcher.Samples.csproj
- media/stitcher/api/Stitcher.Samples/UpdateCdnKey.cs
- media/stitcher/api/Stitcher.Samples/UpdateSlate.cs
- media/stitcher/api/Stitcher.sln
- media/stitcher/api/runTests.ps1
b:202972981
Part 1 of 3: Slates and CDN keys. See also https://cloud.google.com/video-stitcher/docs/how-to/managing-slates and https://cloud.google.com/video-stitcher/docs/how-to/managing-cdn-keys
API must be enabled in test project.
> feat(Video Stitcher): Add samples and tests

- retail/interactive-tutorial/RetailEvents.Samples/ImportUserEventsBigQuerySample.cs
- retail/interactive-tutorial/RetailEvents.Samples/ImportUserEventsGcsSample.cs
- retail/interactive-tutorial/RetailEvents.Samples/ImportUserEventsInlineSourceSample.cs
- retail/interactive-tutorial/RetailEvents.Samples/PurgeUserEventSample.cs
- retail/interactive-tutorial/RetailEvents.Samples/RejoinUserEventSample.cs
- retail/interactive-tutorial/RetailEvents.Samples/WriteUserEventSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/AddFulfillmentPlacesSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/CreateProductSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/CrudProductSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/DeleteProductSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/GetProductSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/ImportProductsBigQueryTableSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/ImportProductsGcsSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/ImportProductsInlineSourceSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/RemoveFulfillmentPlacesSample.cs
- retail/interactive-tutorial/RetailProducts.Samples/SetInventorySample.cs
- retail/interactive-tutorial/RetailProducts.Samples/UpdateProductSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchSimpleQuerySample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithBoostSpecSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithFacetSpecSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithFilteringSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithNextPageTokenSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithOffsetSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithOrderingSample.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithQueryExpansionSample.cs
Remove region tags from: 
- RetailEvents samples
- RetailProducts samples
- RetailSearch samples
> Remove region tags from retail samples

- iot/api/CloudIotMqttExampleTest/runTests.ps1
- iot/api/CloudIotTest/runTests.ps1
Product is being retired and samples will be removed in #1863 as soon as they are removed from docs. Closes #1621
> chore(IoT): Deactivate tests.

- retail/interactive-tutorial/user_environment_setup.sh
Updated user_environment_setup.sh, so we can run script more than once.
> Update user env setup

- retail/interactive-tutorial/RetailSearch.Samples.Tests/SearchWithPaginationTest.cs
- retail/interactive-tutorial/RetailSearch.Samples/SearchWithPaginationSample.cs
SearchWithPageSizeSample.cs was renamed according to tutorials and code samples in other languages.
> Rename SearchWithPageSize sample

- spanner/api/Spanner.Samples.Tests/CreateInstanceConfigAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/DeleteInstanceConfigAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/ListInstanceConfigOperationsAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/ListInstanceConfigsTest.cs
- spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
- spanner/api/Spanner.Samples.Tests/UpdateInstanceConfigAsyncTest.cs
- spanner/api/Spanner.Samples/CreateInstanceConfigAsync.cs
- spanner/api/Spanner.Samples/DeleteInstanceConfigAsync.cs
- spanner/api/Spanner.Samples/ListInstanceConfigOperationsAsync.cs
- spanner/api/Spanner.Samples/ListInstanceConfigs.cs
- spanner/api/Spanner.Samples/UpdateInstanceConfigAsync.cs
Creating new PR from changes of #1717 as these are really old and are causing lot of conflicts while pulling in current main
> Spanner CMMR2 changes

- media/livestream/api/LiveStream.Samples.Tests/CreateChannelWithBackupInputAsyncTests.cs
- media/livestream/api/LiveStream.Samples/CreateChannelWithBackupInputAsync.cs
See also https://cloud.google.com/livestream/docs/how-to/configure-backup-stream
> feat(Livestream): Add sample for creating a channel with a backup input

- firestore/api/AddData/Program.cs
- firestore/api/DataModel/Program.cs
- firestore/api/DeleteData/Program.cs
- firestore/api/GetData/Program.cs
- firestore/api/ListenData/Program.cs
- firestore/api/OrderLimitData/Program.cs
- firestore/api/PaginateData/Program.cs
- firestore/api/QueryData/Program.cs
- firestore/api/Quickstart/Program.cs
- firestore/api/SolutionCounter/Program.cs
- firestore/api/TransactionsAndBatchedWrites/Program.cs
Adding in region tags with standard product prefix for Sample Browser.
> chore: adding standardized region tags

- storage/api/Storage.Samples.Tests/GetAutoclassTest.cs
- storage/api/Storage.Samples.Tests/SetAutoclassTest.cs
- storage/api/Storage.Samples.Tests/StorageFixture.cs
- storage/api/Storage.Samples/GetAutoclass.cs
- storage/api/Storage.Samples/SetAutoclass.cs
Added  samples that demonstrate the following functionality:
- Enabling autoclass for a storage bucket
- Retrieving autoclass data of a storage bucket
> Storage Autoclass samples

- spanner/api/Spanner.Samples.Tests/AddJsonbColumnAsyncPostgreTest.cs
- spanner/api/Spanner.Samples.Tests/CreateInterleavedTablesAsyncPostgreTest.cs
- spanner/api/Spanner.Samples.Tests/QueryJsonbDataUsingParameterAsyncPostgreTest.cs
- spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
- spanner/api/Spanner.Samples.Tests/UpdateDataWithJsonbAsyncPostgreTest.cs
- spanner/api/Spanner.Samples/AddJsonbColumnAsyncPostgre.cs
- spanner/api/Spanner.Samples/QueryJsonbDataUsingParameterAsyncPostgre.cs
- spanner/api/Spanner.Samples/UpdateDataWithJsonbAsyncPostgre.cs
The PR will not compile as PgJsonb changes are not released yet. The idea is to get the sample code reviewed. Thanks.
> feat:PgJsonb samples

- applications/clouddemo/net4/CloudDemo.Mvc/Properties/PublishProfiles/PackageProfile.pubxml
- Fix package name (CloudDemo.Mvc)
- Specify AppPath (/)
> Fix publishing profile of CloudDemo app

- appengine/flexible/Pubsub/Controllers/HomeController.cs
> docs: typo

- applications/clouddemo/netcore/.dockerignore
> Update dockerignore to use net6.0 publishing path

- spanner/api/Spanner.Samples.Tests/DeleteUsingDmlReturningAsyncPostgreTest.cs
- spanner/api/Spanner.Samples.Tests/DeleteUsingDmlReturningAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/ExecutePartitionedDmlAsyncPostgreTest.cs
- spanner/api/Spanner.Samples.Tests/InsertUsingDmlReturningAsyncPostgreTest.cs
- spanner/api/Spanner.Samples.Tests/InsertUsingDmlReturningAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/LogCommitStatsAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
- spanner/api/Spanner.Samples.Tests/UpdateUsingDmlReturningAsyncPostgreTest.cs
- spanner/api/Spanner.Samples.Tests/UpdateUsingDmlReturningAsyncTest.cs
- spanner/api/Spanner.Samples/CreateDatabaseAsync.cs
- spanner/api/Spanner.Samples/CreateDatabaseAsyncPostgre.cs
- spanner/api/Spanner.Samples/DeleteUsingDmlReturningAsync.cs
- spanner/api/Spanner.Samples/DeleteUsingDmlReturningAsyncPostgre.cs
- spanner/api/Spanner.Samples/ExecutePartitionedDmlAsyncPostgre.cs
- spanner/api/Spanner.Samples/InsertUsingDmlReturningAsync.cs
- spanner/api/Spanner.Samples/InsertUsingDmlReturningAsyncPostgre.cs
- spanner/api/Spanner.Samples/UpdateUsingDmlReturningAsync.cs
- spanner/api/Spanner.Samples/UpdateUsingDmlReturningAsyncPostgre.cs
This PR contains:-
- Samples for DML Returning.
- Tests for new samples.
> feat: Samples for DML Returning

- cdn/signUrl/SignUrlSample/Program.cs
Old region tags are replaced with product specific region tags. Please check b/272509882 for more details.
New Region tags were added using Pull Request: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/2089/files
fixes: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/2095
> chore: cleanup un-wanted region tags

- spanner/api/Spanner.Samples.Tests/QueryDataWithTimestampColumnAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/QueryNewColumnAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/ReadStaleDataAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/ReadWriteWithTransactionAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/ReadWriteWithTransactionCoreAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
- spanner/api/Spanner.Samples.Tests/UpdateDataAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/UpdateDataWithTimestampColumnTest.cs
- spanner/api/Spanner.Samples.Tests/UpdateUsingBatchDmlCoreAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/UpdateUsingDmlCoreAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/UpdateUsingDmlWithTimestampCoreAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/UpdateUsingPartitionedDmlCoreAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/WriteWithTransactionUsingDmlCoreAsyncTest.cs
This resolves the issue https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/2021
> fix: spanner integration test conflict resolution

- bigquery/api/SimpleApp/Program.cs
updated the big query sample to fetch project id from env variable.
> chore: update bigquery quickstart to fetch project id from env variable

- media/transcoder/api/Transcoder.Samples/CreateJobWithAnimatedOverlay.cs
- media/transcoder/api/Transcoder.Samples/CreateJobWithStaticOverlay.cs
> docs: remove restriction of JPEGs only for overlay images

- bigquery/api/SimpleApp/runTests.ps1
updated quick start to use the Google_Cloud_Project env variable directly.
made the corresponding changes in  runTest.ps1 as well. 
The test is running fine locally.
> chore: updated runTests.ps1 file of bigquery Quickstart

- .kokoro/main.ps1
> ci: Fix script so that CI runs in Windows again

- cloud-sql/mysql/README.md
- cloud-sql/postgres/README.md
- logging/api/WithGitId/README.md
Fixing typos on:
cloud-sql/mysql/README.md
cloud-sql/postgres/README.md
logging/api/WithGitId/README.md
> Fixing typos

- .kokoro/main.ps1
A couple of folders are still popping up as modified because of line endings.
> ci: Improves Windows CI so that tests are only run for modifications.

- dlp/api/Snippets.Tests/InspectPhoneNumberTests.cs
- dlp/api/Snippets/InspectPhoneNumber.cs
- Added sample for [inspect phone number](https://cloud.google.com/dlp/docs/samples/dlp-inspect-phone-number) with tests.
> DLP: Added sample for Inspect phone number

- dlp/api/Snippets.Tests/InspectDataWithCustomRegexTests.cs
- dlp/api/Snippets/InspectDataWithCustomRegex.cs
- Added sample for [Inspect Custom Regex](https://cloud.google.com/dlp/docs/creating-custom-infotypes-regex#dlp-inspect-custom-regex-java) and unit tests
> DLP: Added sample for Inspect custom regex

- dlp/api/Snippets.Tests/DeidentifyTableUsingMaskingAndLogicTests.cs
- dlp/api/Snippets/DeidentifyTableUsingMaskingAndLogic.cs
- Added sample for [Deidentify Table Using Condition and Masking](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_a_column_based_on_the_value_of_another_column) and unit tests
> DLP: Added sample for deidentify table using condition and masking

- dlp/api/Snippets.Tests/InspectTableTests.cs
- dlp/api/Snippets/InspectTable.cs
- Added sample for [Inspect Table](https://cloud.google.com/dlp/docs/inspecting-structured-text.md#dlp-inspect-table-java) and test cases
> DLP: Added sample for inspect table

- dlp/api/Snippets.Tests/DlpTestFixture.cs
- dlp/api/Snippets.Tests/InspectBigQueryWithSamplingTests.cs
- dlp/api/Snippets/InspectBigQueryWithSampling.cs
- dlp/api/Snippets/README.md
- Added sample for [Inspect Big Query With Sampling](https://cloud.google.com/dlp/docs/inspecting-storage#limiting-bq) with test cases
> DLP: Added sample for inspect big query with sampling

- .github/renovate.json
> fix: Renovate config JSON missing a comma.

- dlp/api/Snippets.Tests/DlpTestFixture.cs
- dlp/api/Snippets.Tests/InspectStorageWithSamplingTests.cs
- dlp/api/Snippets/InspectStorageWithSampling.cs
- dlp/api/Snippets/README.md
- Added sample for [Inspect Storage With Sampling](https://cloud.google.com/dlp/docs/inspecting-storage.md#dlp_inspect_gcs_with_sampling-java) with test cases
> DLP: Added sample for inspect storage with sampling

- dlp/api/Snippets.Tests/ReidentifyContentUsingFpeTests.cs
- dlp/api/Snippets.Tests/runTest.ps1
- dlp/api/Snippets/README.md
- dlp/api/Snippets/ReidentifyContentUsingFpe.cs
- Added sample for [Reidentify Content Using FPE](https://cloud.google.com/dlp/docs/samples/dlp-reidentify-fpe) and test cases
> DLP: Added sample for reidentify content using fpe

- dlp/api/Snippets.Tests/DeidentifyWithDateShiftTests.cs
- dlp/api/Snippets.Tests/DeidentifyWithFpeTests.cs
- This PR has the fix for the issue https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/510
> DLP: Fix of the issue #510

- dlp/api/Snippets.Tests/DeidentifyWithTimeExtractionTests.cs
- dlp/api/Snippets/DeidentifyWithTimeExtraction.cs
- Added sample for [Deidentify Table With Time Extraction](https://cloud.google.com/dlp/docs/transformations-reference#time-extract) and test cases
> DLP: Added sample for deidentify table with time extraction

- logging/api/LoggingSample/Program.cs
> fix: Update logging sample to use structured logging.

- dlp/api/Snippets.Tests/DeidentifyTableWithFpeTests.cs
- dlp/api/Snippets/DeidentifyTableWithFpe.cs
- Added sample for [Deidentify Table With FPE](https://cloud.google.com/dlp/docs/samples/dlp-deidentify-table-fpe) and test cases
> DLP: Added sample for deidentify table with fpe

- dlp/api/Snippets.Tests/DeidentifyTableWithCryptoHashTests.cs
- dlp/api/Snippets/DeidentifyTableWithCryptoHash.cs
- Added sample for [Deidentify Table with Crypto Hash](https://cloud.google.com/dlp/docs/examples-deid-tables.md#transform_findings_using_a_cryptographic_hash_transformation) and test cases
> DLP: Added sample for deidentify table with crypto hash

- dlp/api/Snippets.Tests/ClientLibraryQuickStartTests.cs
- dlp/api/Snippets/ClientLibraryQuickStart.cs
- Added sample for [QuickStart DLP Library](https://cloud.google.com/dlp/docs/samples/dlp-quickstart) and test cases
> DLP: Added sample for QuickStart DLP  library

- dlp/api/Snippets.Tests/InspectBigQueryWithSCCIntegrationTests.cs
- dlp/api/Snippets.Tests/runTest.ps1
- dlp/api/Snippets/InspectBigQueryWithSCCIntergration.cs
- Added sample for [Inspect Big Query Data and Send to SCC](https://cloud.google.com/dlp/docs/sending-results-to-scc.md#bigquery-data) with test cases
> DLP: Added sample for inspect big query table with SCC integration

- media/transcoder/api/Transcoder.Samples.Tests/CreateJobFromPresetBatchModeTests.cs
- media/transcoder/api/Transcoder.Samples.Tests/Transcoder.Samples.Tests.csproj
- media/transcoder/api/Transcoder.Samples/CreateJobFromPresetBatchMode.cs
b:288111390
Please merge on approval.
> feat(Transcoder): Add batch mode sample and test

- dlp/api/Snippets.Tests/SendDataToTheHybridJobTriggerTests.cs
- dlp/api/Snippets/SendDataToTheHybridJobTrigger.cs
- Added sample of [Inspect Data Using Hybrid Job Trigger](https://cloud.google.com/dlp/docs/how-to-hybrid-jobs#formatting) and test cases
> DLP: Added sample of inspect data using hybrid job trigger

- dlp/api/Snippets.Tests/CreateStoredInfoTypesTests.cs
- dlp/api/Snippets.Tests/InspectDataWithStoredInfotypesTests.cs
- dlp/api/Snippets.Tests/UpdateStoredInfoTypesTests.cs
- Fix PR to solve the problem of deletion of bucket before deleting the objects inside it.
> DLP: Fixed test cases where bucket deletion process was failing

- dlp/api/Snippets.Tests/CalculateKAnonymityOnDatasetTests.cs
- dlp/api/Snippets/CalculateKAnonymityOnDataset.cs
- Added sample for [Calculating k-anonymity on the dataset](https://cloud.google.com/dlp/docs/visualizing_re-id_risk.md?g=0&l=119#step_1_calculate_k-anonymity_on_the_dataset) and test cases
> DLP: Added sample for calculating k-anonymity on dataset

- dlp/api/Snippets.Tests/TriggersUpdateTests.cs
- dlp/api/Snippets/TriggersUpdate.cs
- Added sample for [Update Trigger](https://cloud.google.com/dlp/docs/creating-job-triggers#update_an_existing_job_trigger) and unit test cases.
> DLP: Added sample for update trigger

- dlp/api/Snippets.Tests/InspectStorageWithSCCIntegrationTests.cs
- dlp/api/Snippets/InspectStorageWithSCCIntegration.cs
- Added sample for [Inspect Storage with SCC Integration](https://cloud.google.com/dlp/docs/sending-results-to-scc.md#cloud-storage-data) and test cases
> DLP: Added sample for inspect storage with SCC integration

- dlp/api/Snippets.Tests/DeidentifyDataStoredInCloudStorageTests.cs
- dlp/api/Snippets.Tests/resources/test.txt
- dlp/api/Snippets/DeidentifyDataStoredInCloudStorage.cs
- Added sample for [Deidentify Data Stored in Cloud Storage](https://cloud.google.com/dlp/docs/deidentify-storage#code-example) and test cases
> DLP: Added sample for deidentify data stored in cloud storage

- error-reporting/api/ErrorReportingSample/ErrorReportingSample.cs
align code sample for error reporting with code in other languages (b/275730159):
1. use an exception with "fixed" message
1. report error context
1. follow best practices for the language to report service context
> fix: refactor error reporting code sample

- dlp/api/Snippets/RedactImage.cs
- Fixed indentation in dlp_redact_image
> DLP: Fixed indentation in dlp_redact_image

- storage/api/Storage.Samples.Tests/GetAutoclassTest.cs
- storage/api/Storage.Samples.Tests/SetAutoclassTest.cs
- storage/api/Storage.Samples/GetAutoclass.cs
- storage/api/Storage.Samples/SetAutoclass.cs
This add support for autoclass v2.1, it will resolve https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/2341
> feat: add Autoclass v2.1 support

- CODEOWNERS
I am no longer working on these projects, so I am not the best reviewer.
> Remove sethvargo from CODEOWNERS

- pubsub/api/Pubsub.Samples.Tests/CreateSubscriptionWithDeadLetterPolicyTest.cs
- pubsub/api/Pubsub.Samples.Tests/CreateSubscriptionWithOrderingTest.cs
- pubsub/api/Pubsub.Samples.Tests/PullMessagesAsyncWithDeliveryAttemptsTest.cs
- pubsub/api/Pubsub.Samples.Tests/RemoveDeadLetterPolicyTest.cs
- pubsub/api/Pubsub.Samples.Tests/UpdateDeadLetterPolicyTest.cs
- pubsub/api/Pubsub.Samples/CreateSubscriptionWithDeadLetterPolicy.cs
- pubsub/api/Pubsub.Samples/CreateSubscriptionWithOrdering.cs
This tripped me up due to a copy/paste problem when creating another sample.
> chore: Make topic/subscription ordering consistent

- pubsub/api/Pubsub.Samples.Tests/CreateUnwrappedPushSubscriptionTest.cs
- pubsub/api/Pubsub.Samples/CreateUnwrappedPushSubscription.cs
> docs(pubsub): Add CreateUnwrappedPushSubscription sample

- pubsub/api/Pubsub.Samples.Tests/CreateTopicWithSchemaRevisionsTest.cs
- pubsub/api/Pubsub.Samples.Tests/SubscribeAvroRecordsWithRevisionsTest.cs
- pubsub/api/Pubsub.Samples.Tests/SubscriberConcurrencyControlTest.cs
- pubsub/api/Pubsub.Samples.Tests/UpdateTopicSchemaTest.cs
- pubsub/api/Pubsub.Samples/CreateTopicWithSchemaRevisions.cs
- pubsub/api/Pubsub.Samples/ExactlyOnceDeliverySubscriberAsync.cs
- pubsub/api/Pubsub.Samples/PublishAvroMessagesAsync.cs
- pubsub/api/Pubsub.Samples/PublishMessagesAsync.cs
- pubsub/api/Pubsub.Samples/PublishProtoMessagesAsync.cs
- pubsub/api/Pubsub.Samples/PullMessageWithLeaseManagement.cs
- pubsub/api/Pubsub.Samples/PullMessagesAsync.cs
- pubsub/api/Pubsub.Samples/PullMessagesAsyncWithDeliveryAttempts.cs
- pubsub/api/Pubsub.Samples/PullMessagesSync.cs
- pubsub/api/Pubsub.Samples/PullMessagesWithCustomAttributesAsync.cs
- pubsub/api/Pubsub.Samples/PullMessagesWithFlowControlAsync.cs
- pubsub/api/Pubsub.Samples/Resources/us-states-new.avsc
- pubsub/api/Pubsub.Samples/SubscribeAvroRecordsWithRevisions.cs
- pubsub/api/Pubsub.Samples/SubscriberConcurrencyControl.cs
- pubsub/api/Pubsub.Samples/UpdateTopicSchema.cs
- pubsub/api/Pubsub.Samples/Utilities/StateUtils.cs
- testutil/TestUtil.cs
As ever, review one commit at a time.
> docs(pubsub): Add four more samples

- pubsub/api/Pubsub.Samples.Tests/ListSchemaRevisionsTest.cs
- pubsub/api/Pubsub.Samples/ListSchemaRevisions.cs
> tests: Implement pubsub_list_schema_revisions sample

- spanner/api/QuickStart/QuickStart.csproj
- spanner/api/Spanner.Samples/CommitDelayAsync.cs
- spanner/api/Spanner.Samples/Spanner.Samples.csproj
> fix[Spanner]: Update commit delay sample.

- storage/api/Storage.Samples.Tests/CreateBucketWithObjectRetentionTest.cs
- storage/api/Storage.Samples.Tests/SetObjectRetentionPolicyTest.cs
- storage/api/Storage.Samples/CreateBucketWithObjectRetention.cs
- storage/api/Storage.Samples/GetBucketMetadata.cs
- storage/api/Storage.Samples/GetMetadata.cs
- storage/api/Storage.Samples/SetObjectRetentionPolicy.cs
Adds samples for object retention along with tests
Fixes https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/2501
> feat(storage): Add samples for object retention

- aiplatform/api/AIPlatform.Samples.Tests/AudioInputSummarizationTest.cs
- aiplatform/api/AIPlatform.Samples.Tests/AudioInputTranscriptionTest.cs
- aiplatform/api/AIPlatform.Samples.Tests/MultimodalAllInputTest.cs
- aiplatform/api/AIPlatform.Samples.Tests/PdfInputTest.cs
- aiplatform/api/AIPlatform.Samples.Tests/SystemInstructionTest.cs
- aiplatform/api/AIPlatform.Samples.Tests/VideoInputWithAudioTest.cs
- aiplatform/api/AIPlatform.Samples/AudioInputSummarization.cs
- aiplatform/api/AIPlatform.Samples/AudioInputTranscription.cs
- aiplatform/api/AIPlatform.Samples/MultimodalAllInput.cs
- aiplatform/api/AIPlatform.Samples/PdfInput.cs
- aiplatform/api/AIPlatform.Samples/SystemInstruction.cs
- aiplatform/api/AIPlatform.Samples/VideoInputWithAudio.cs
* Added some samples for Gemini 1.5. 
* They're all very similar samples with slight differences, that's why I'm doing it in a single PR. 
* Fixes b/336757387, b/336757211, b/336757534, b/336757434, b/336758092
> Added samples for Gemini 1.5

- aiplatform/api/AIPlatform.Samples/AudioInputSummarization.cs
- aiplatform/api/AIPlatform.Samples/AudioInputTranscription.cs
- aiplatform/api/AIPlatform.Samples/GeminiQuickstart.cs
- aiplatform/api/AIPlatform.Samples/MultiTurnChatSample.cs
- aiplatform/api/AIPlatform.Samples/MultimodalAllInput.cs
- aiplatform/api/AIPlatform.Samples/MultimodalVideoInput.cs
- aiplatform/api/AIPlatform.Samples/PdfInput.cs
- aiplatform/api/AIPlatform.Samples/PredictCodeCompletionCommentSample.cs
- aiplatform/api/AIPlatform.Samples/SystemInstruction.cs
- aiplatform/api/AIPlatform.Samples/VideoInputWithAudio.cs
Fixing minor style issues in the Gemini samples
> Fix code style in all AIPlatform.Samples #2622

- aiplatform/api/AIPlatform.Samples.Tests/AIPlatform.Samples.Tests.csproj
- aiplatform/api/AIPlatform.Samples.Tests/TextInputTest.cs
- aiplatform/api/AIPlatform.Samples/TextInputSample.cs
Fixes b:336785030
Please merge on approval.
> feat: add gemini code sample and test for text-only input

- aiplatform/api/AIPlatform.Samples/AudioInputSummarization.cs
- aiplatform/api/AIPlatform.Samples/AudioInputTranscription.cs
- aiplatform/api/AIPlatform.Samples/GeminiQuickstart.cs
- aiplatform/api/AIPlatform.Samples/MultiTurnChatSample.cs
- aiplatform/api/AIPlatform.Samples/MultimodalAllInput.cs
- aiplatform/api/AIPlatform.Samples/MultimodalMultiImage.cs
- aiplatform/api/AIPlatform.Samples/MultimodalVideoInput.cs
- aiplatform/api/AIPlatform.Samples/PdfInput.cs
- aiplatform/api/AIPlatform.Samples/SystemInstruction.cs
- aiplatform/api/AIPlatform.Samples/VideoInputWithAudio.cs
- aiplatform/api/AIPlatform.Samples/WithSafetySettings.cs
Updated all samples to initialize requests inline per @jskeet's suggestion
> docs(aiplatform): Change all samples to use inline initialization #2626

- aiplatform/api/AIPlatform.Samples.Tests/TextInputTest.cs
- aiplatform/api/AIPlatform.Samples/TextInputSample.cs
Fixes b/336785030#comment8
Please merge this PR for me once it is approved
> feat: refactor text-only Gemini prompt

- aiplatform/api/AIPlatform.Samples.Tests/FunctionCallingTest.cs
- aiplatform/api/AIPlatform.Samples/FunctionCalling.cs
> docs(aiplatform): Add FunctionCalling sample 

- aiplatform/api/AIPlatform.Samples.Tests/MultimodalAllInputTest.cs
- aiplatform/api/AIPlatform.Samples/AudioInputSummarization.cs
- aiplatform/api/AIPlatform.Samples/AudioInputTranscription.cs
- aiplatform/api/AIPlatform.Samples/MultimodalAllInput.cs
- aiplatform/api/AIPlatform.Samples/PdfInput.cs
- aiplatform/api/AIPlatform.Samples/SystemInstruction.cs
- aiplatform/api/AIPlatform.Samples/TextInputSample.cs
- aiplatform/api/AIPlatform.Samples/VideoInputWithAudio.cs
Update samples to use Gemini 1.5 Flash
> Update C# samples for Gemini 1.5 GA

- storage/api/Storage.Samples.Tests/CreateBucketWithHierarchicalNamespaceEnabledTest.cs
- storage/api/Storage.Samples/CreateBucketWithHierarchicalNamespaceEnabled.cs
Adds a sample for hierarchical namespace configuration
> feat(storage): add HNS sample

- storage/api/Storage.Samples.Tests/StorageControlCreateFolderTest.cs
- storage/api/Storage.Samples.Tests/StorageControlDeleteFolderTest.cs
- storage/api/Storage.Samples.Tests/StorageControlGetFolderTest.cs
- storage/api/Storage.Samples.Tests/StorageControlListFoldersTest.cs
- storage/api/Storage.Samples.Tests/StorageControlRenameFolderTest.cs
- storage/api/Storage.Samples.Tests/StorageFixture.cs
- storage/api/Storage.Samples/StorageControlCreateFolder.cs
- storage/api/Storage.Samples/StorageControlDeleteFolder.cs
- storage/api/Storage.Samples/StorageControlGetFolder.cs
- storage/api/Storage.Samples/StorageControlListFolders.cs
- storage/api/Storage.Samples/StorageControlRenameFolder.cs
Adds samples for the Folders feature in storage control
> feat(storagecontrol): Folders samples

- firestore/api/AddData/Program.cs
- firestore/api/FirestoreTest/FirestoreTest.cs
- firestore/api/QueryData/Program.cs
(The first two commits are tidying up. There's still a lot I'd want to change in the Firestore sample organization, but this was intended to be a light-touch change.)
> docs: Add firestore_query_subcollection snippet

- aiplatform/api/AIPlatform.Samples.Tests/ControllerGenerationTest.cs
- aiplatform/api/AIPlatform.Samples/ControlledGeneration.cs
Code cleanup of unused AI code sample
More details: [b351822519](http://b/351822519)
> chore: codecleanup of unused AI Samples

- endpoints/getting-started/src/runTests.ps1
- getting-started/background-processing/TranslateUI/runTests.ps1
- getting-started/background-processing/TranslateWorker/runTests.ps1
> chore: .NET 8 upgrade follow up

- aiplatform/api/AIPlatform.Samples.Tests/MultimodalAllInputTest.cs
> Look for another more probable string in the output

- media/stitcher/api/Stitcher.Samples/ListCdnKeys.cs
- media/stitcher/api/Stitcher.Samples/ListLiveAdTagDetails.cs
- media/stitcher/api/Stitcher.Samples/ListLiveConfigs.cs
- media/stitcher/api/Stitcher.Samples/ListSlates.cs
Address https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/2739#discussion_r1690260288
> feat(Video Stitcher): add list iterators to list samples

- aiplatform/api/AIPlatform.Samples.Tests/ContextCacheTest.cs
- aiplatform/api/AIPlatform.Samples/AIPlatform.Samples.csproj
- aiplatform/api/AIPlatform.Samples/ContextCaching/CreateContextCache.cs
- aiplatform/api/AIPlatform.Samples/ContextCaching/DeleteContextCache.cs
- aiplatform/api/AIPlatform.Samples/ContextCaching/GetContextCache.cs
- aiplatform/api/AIPlatform.Samples/ContextCaching/UpdateContextCache.cs
- aiplatform/api/AIPlatform.Samples/ContextCaching/UseContextCache.cs
> Implement context caching samples and tests

- spanner/api/Spanner.Samples/Spanner.Samples.csproj
> chore: Fix Spanner build by ignoring warnings for now

- aiplatform/api/AIPlatform.Samples.Tests/VideoInputWithAudioTest.cs
> Loosen up the test for the build

- datastore/admin-api/DatastoreAdmin.Samples/ImportEntities.cs
> chore[Datastore Admin]: Stop refering to a specific bucket name

- spanner/api/Spanner.Samples.Tests/CreateInstanceAsyncTest.cs
- spanner/api/Spanner.Samples.Tests/CreateInstancePartitionTest.cs
- spanner/api/Spanner.Samples.Tests/CreateInstanceWithProcessingUnitsTest.cs
- spanner/api/Spanner.Samples.Tests/SpannerFixture.cs
- spanner/api/Spanner.Samples.Tests/UpdateInstanceAsyncTest.cs
- spanner/api/Spanner.Samples/CreateInstanceAsync.cs
- spanner/api/Spanner.Samples/UpdateInstanceAsync.cs
And creates the Instances we use for testing in the Enterprise Plus edition.
Minor refactoring of fixture code.
Closes b/331523930
Fixes b/371116134
> feat[Spanner]: Add edition samples and tests

- spanner/api/Spanner.Samples.Tests/CreateInstanceWithoutDefaultBackupSchedulesTest.cs
- spanner/api/Spanner.Samples.Tests/UpdateInstanceDefaultBackupScheduleTypeTest.cs
- spanner/api/Spanner.Samples/CreateInstanceWithoutDefaultBackupSchedules.cs
- spanner/api/Spanner.Samples/UpdateInstanceDefaultBackupScheduleType.cs
This PR contains create and update instance samples for Spanner default backup schedules.
> feat(Spanner): Add samples for Cloud Spanner Default Backup Schedules

- .github/blunderbuss.yml
- CODEOWNERS
> chore(media): Update codeowners

- .github/blunderbuss.yml
- CODEOWNERS
Replace outdated cloud-storage-dpe group
> chore: set gcs-sdk-team as CODEOWNERS

- CODEOWNERS
Addresses b/405801293
Requires team to be added to repo with write access
> chore: add cloud-samples-infra to CODEOWNERS

- pubsub/api/Pubsub.Samples.Tests/PubsubFixture.cs
Needed for pubsub_update_topic_type sample and pubsub_create_topic_with_kinesis_ingestion
> tests(PubSub): Adds RandomKinesisIngestionParams method to PubSubFixture

- functions/helloworld/HelloPubSubFSharp/HelloPubSubFSharp.fsproj
- functions/helloworld/HelloPubSubVb/HelloPubSubVb.vbproj
- functions/helloworld/HelloWorldFSharp/HelloWorldFSharp.fsproj
- functions/helloworld/HelloWorldVb/HelloWorldVb.vbproj
This were leftover for some reason.
> build(Functions Framework): Update some samples to target .NET 8.

- pubsub/api/Pubsub.Samples/PullAvroMessagesAsync.cs
https://buganizer.corp.google.com/issues/376027437
> feat(PubSub): Add comments about AvroUtilities on PullAvroMessagesAsync sample

- pubsub/api/Pubsub.Samples/ExactlyOnceDeliverySubscriberAsync.cs
> fix(PubSub): Add locational endpoint to ExactlyOnceDeliverySubscriberAsync sample

- pubsub/api/Pubsub.Samples.Tests/CreateTopicWithCloudStorageIngestionTest.cs
- pubsub/api/Pubsub.Samples/CreateTopicWithCloudStorageIngestion.cs
https://cloud.google.com/pubsub/docs/samples/pubsub-create-topic-with-cloud-storage-ingestion
> feat(PubSub): Add CreateTopicWithCloudStorageIngestion Sample

- pubsub/api/Pubsub.Samples.Tests/CreateTopicWithAzureEventHubsIngestionTest.cs
- pubsub/api/Pubsub.Samples/CreateTopicWIthAzureEventHubsIngestion.cs
https://cloud.google.com/pubsub/docs/samples/pubsub-create-topic-with-azure-event-hubs-ingestion
This PR depends on #3044
> feat(PubSub): Add CreateTopicWithAzureEventHubs Sample

- pubsub/api/Pubsub.Samples.Tests/CreateTopicWithConfluentCloudIngestionTest.cs
- pubsub/api/Pubsub.Samples/CreateTopicWithConfluentCloudIngestion.cs
https://cloud.google.com/pubsub/docs/samples/pubsub-create-topic-with-confluent-cloud-ingestion
This PR depends on: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/3044
> feat(PubSub): Add CreateTopicWithConfluentCloudIngestion Sample

- pubsub/api/Pubsub.Samples.Tests/CreateTopicWithAwsMskIngestionTest.cs
- pubsub/api/Pubsub.Samples/CreateTopicWithAwsMskIngestion.cs
https://cloud.google.com/pubsub/docs/samples/pubsub-create-topic-with-aws-msk-ingestion
This PR is dependent on: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/3044
> feat(PubSub): Add CreateTopicWithAwsMskIngestion Sample

- pubsub/api/Pubsub.Samples.Tests/UpdateTopicTypeTest.cs
- pubsub/api/Pubsub.Samples/UpdateTopicType.cs
https://cloud.google.com/pubsub/docs/samples/pubsub-update-topic-type
> feat(PubSub): Add UpdateTopicType Sample

- pubsub/api/Pubsub.Samples.Tests/OptimisticSubscribeTest.cs
- pubsub/api/Pubsub.Samples/OptimisticSubscribe.cs
https://cloud.google.com/pubsub/docs/samples/pubsub-optimistic-subscribe
> feat(PubSub): Add OptimisticSubscribe Sample

- pubsub/api/Pubsub.Samples.Tests/SubscriberErrorListenerTest.cs
- pubsub/api/Pubsub.Samples/SubscriberErrorListener.cs
PubSub SubscriberErrorListener Sample
https://cloud.google.com/pubsub/docs/samples/pubsub-subscriber-error-listener#pubsub_subscriber_error_listener-java
> feat(PubSub): Add SubscriberErrorListener Sample

- parametermanager/README.md
It has no meaningful information at the moment.
> chore: Delete parametermanager/README.md

- modelarmor/api/ModelArmor.Samples.Tests/CreateTemplateWithAdvanceSdpTest.cs
- modelarmor/api/ModelArmor.Samples.Tests/CreateTemplateWithBasicSdpTest.cs
- modelarmor/api/ModelArmor.Samples.Tests/ModelArmor.Samples.Tests.csproj
- modelarmor/api/ModelArmor.Samples.Tests/ModelArmorFixture.cs
- modelarmor/api/ModelArmor.Samples.Tests/QuickStartTest.cs
- modelarmor/api/ModelArmor.Samples/CreateTemplateWithAdvancedSdp.cs
- modelarmor/api/ModelArmor.Samples/CreateTemplateWithBasicSdp.cs
- modelarmor/api/ModelArmor.Samples/ModelArmor.Samples.csproj
- modelarmor/api/ModelArmor.Samples/QuickStart.cs
Added following Model Armor Snippets:
- Create Template with basic SDP
- Create Template with advanced SDP
> feat(modelarmor): Added snippets to create template with basic and advanced SDP

- media/stitcher/api/Stitcher.Samples.Tests/CreateCdnKeyAkamaiAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/CreateCdnKeyAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/CreateLiveConfigAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/CreateSlateAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/CreateVodConfigAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/DeleteCdnKeyAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/DeleteLiveConfigAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/DeleteSlateAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/DeleteVodConfigAsyncTests.cs
- media/stitcher/api/Stitcher.Samples.Tests/StitcherFixture.cs
- media/stitcher/api/Stitcher.sln
Whoever gets to review, one commit at a time should be clearer.
Fixes b/423630286
> fix(Video Stitcher): Really delete stale resources.

- bigquery-storage/api/BigQueryStorage.Samples/AppendRowsPending.cs
https://buganizer.corp.google.com/issues/330686093
> chore(BigQuery): Log row level errors in AppendRowsPendingSample
